### PR TITLE
Fix#1484 Fix slider track label

### LINKED ISSUE #1484: Not working track-label for Slider Range
When add Vuestic UI Slider (range type) no possibility change track-label

`<va-slider
          @change="onChangePrice"
          v-model="price"
          track-label-visible
          :track-label="price + '%'"
          range
        />`

### PR DESCRIPTION
**Pull request by RVitaly1978**
## Description
close #1484

changes:
- [x] add types `Function`, `String`, `Array` to `track-label` prop
- [x] add slot `trackLabel`
- [x] update locales, examples

chrome-capture (1)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any feature but make things better)

### CODE REVIEW

File: packages/ui/src/components/va-slider/VaSlider.vue [hunk 1]
```diff
@@ -682,6 +689,18 @@ export default class VaSlider extends mixins(
...
   }
 
+  getTrackLabel (val: any, order: number) {
+    if (!this.trackLabel) { return val }
+
+    if (typeof this.trackLabel === 'function') {
+      return this.trackLabel(val)
+    }
+
+    return (typeof this.trackLabel === 'string')
```
Comment (asvae) [inline packages/ui/src/components/va-slider/VaSlider.vue:699]: What's the case for that? How track label could be a string?

**Comment by asvae** [comment]
Apart from small things I found - looks good 👍

**Review by LighthouseKeeperYN — APPROVED** [review]
