### PR TITLE
Trap focus in opened modal

### LINKED ISSUE #2139: Background elements receive keyboard focus while VaModal is open
**Vuestic-ui version:** 
@vuestic\nuxt@1.0.3

**Steps to reproduce**
1. Open the `<va-modal>` component while having focusable elements in the background. For example:
```
<template>
  <div>
    <a href="#" />
    <input type="text" />
    <va-modal v-model="isModalOpen" />
  </div>
</template>

<script setup>
const isModalOpen = true;

</script>
```
2. Start tabbing through the website.

**What is the expected behavior?**
The "Ok" and "Cancel"  buttons immediately receive focus.

**What is the current behavior?**
All focusable background elements, such as anchors and inputs receive focus,

**Other information**
While working at my previous work place I faced the same issue and this article proved very helpful. If you guys need any help, I would love to try and contribute :D 
https://www.codementor.io/@zellliew/getting-keyboard-focusable-elements-zell-liew-13bsvuj1lk

### PR DESCRIPTION
**Pull request by Azgiliat**
Fix #2139

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any feature but make things better)

### CODE REVIEW

File: packages/ui/src/composables/useTrapFocus.ts [hunk 1]
```diff
@@ -0,0 +1,92 @@
...
+    }
+  }
+  const focusLastElement = () => {
+    if (lastFocusableElement) {
+      lastFocusableElement.focus()
+    }
+  }
+
+  const onKeydown = (evt: KeyboardEvent) => {
+    const isTabPressed = evt.key === String(TAB_KEYCODE) || evt.keyCode === TAB_KEYCODE
```
Comment (m0ksem) [inline packages/ui/src/composables/useTrapFocus.ts:30]: We can use `KeyboardEvent.code` since we don't need IE support.

```suggestion
    const isTabPressed = evt.code === 'Tab'
```

File: packages/ui/src/composables/useTrapFocus.ts [hunk 2]
```diff
@@ -0,0 +1,92 @@
...
+
+  const trapFocusIn = (el: HTMLElement) => {
+    trapInEl = el
+
+    freeFocus()
+    trapFocus()
+  }
+
+  const trapFocus = () => {
+    nextTick(() => {
```
Comment (m0ksem) [inline packages/ui/src/composables/useTrapFocus.ts:66]: Let's call `nextTick` outside `trapFocus` method e.g. `nextTick(trapFocus)`. 

BTW, why do we need `nextTick`?

File: packages/ui/src/composables/useModalLevel.ts [hunk 3]
```diff
@@ -0,0 +1,27 @@
+import { computed, ref } from 'vue'
+
+const LOWEST_MODAL_LEVEL = 1
+const NO_MODALS_LEVEL = 0
+const currentModalsLevel = ref(NO_MODALS_LEVEL)
+
+export const useModalLevel = () => {
+  const currentModalLevel = ref<null | number>(null)
+  const getModalLevelOnClose = () => {
```
Comment (m0ksem) [inline packages/ui/src/composables/useModalLevel.ts:9]:
```suggestion
  const onModalClose = () => {
```

File: packages/ui/src/composables/useTrapFocus.ts [hunk 4]
```diff
@@ -0,0 +1,92 @@
...
+
+  let focusableElements: HTMLElement[] = []
+  let firstFocusableElement: HTMLElement | null = null
+  let lastFocusableElement: HTMLElement | null = null
+  let isFocusTrapped = false
+
+  const focusFirstElement = () => {
+    if (firstFocusableElement) {
+      firstFocusableElement.focus()
+    }
```
Comment (m0ksem) [inline packages/ui/src/composables/useTrapFocus.ts:21]:
```suggestion
    firstFocusableElement?.focus()
```

File: packages/ui/src/composables/useTrapFocus.ts [hunk 5]
```diff
@@ -0,0 +1,92 @@
...
+  }
+  const focusLastElement = () => {
+    if (lastFocusableElement) {
+      lastFocusableElement.focus()
+    }
```
Comment (m0ksem) [inline packages/ui/src/composables/useTrapFocus.ts:26]:
```suggestion
    lastFocusableElement?.focus()
```

File: packages/ui/src/components/va-modal/VaModal.vue [hunk 6]
```diff
@@ -256,6 +264,19 @@ export default defineComponent({
     const window = useWindow()
     const document = useDocument()
 
+    watch(valueComputed, (newValue) => {
+      // put this into watchEffect -> max recursion stack
```
Comment (m0ksem) [inline packages/ui/src/components/va-modal/VaModal.vue:268]:
```suggestion
```

Yeah, because we don't need to change and reactive variables at the same time in watchEffect.

File: packages/ui/src/components/va-modal/VaModal.vue [hunk 7]
```diff
@@ -270,6 +291,16 @@ export default defineComponent({
           document.value?.body.classList.remove('va-modal-overlay-background--blurred')
         }
       }
+
+      if (isTopLevelModal.value && modalDialog.value) {
```
Comment (m0ksem) [inline packages/ui/src/components/va-modal/VaModal.vue:295]: I think it must be moved to its own `watchEffect`. It looks like it will add or remove window events if `isTopLevelModal` changed. Same with css classes. It will cause a bug with blurred body if we close-open nested modal.

File: packages/ui/src/composables/useModalLevel.ts [hunk 8]
```diff
@@ -0,0 +1,27 @@
...
+    currentModalsLevel.value--
+    currentModalLevel.value = null
+  }
+  const getModalLevelOnOpen = () => {
+    currentModalsLevel.value++
+    currentModalLevel.value = currentModalsLevel.value
```
Comment (m0ksem) [inline packages/ui/src/composables/useModalLevel.ts:15]: > `Will Will Smith smith? Yes, Will Smith will smith`

How about changing `currentModalsLevel` to `theUpperModalLevel`?

**Review by m0ksem — CHANGES_REQUESTED** [review]
Looks good. Let's move trapFocusIn to own watchEffect.

File: packages/ui/src/composables/useTrapFocus.ts (hunk 4 above)
Comment (Azgiliat) [reply packages/ui/src/composables/useTrapFocus.ts]: Changed

File: packages/ui/src/components/va-modal/VaModal.vue (hunk 6 above)
Comment (Azgiliat) [reply packages/ui/src/components/va-modal/VaModal.vue]: Fixed

File: packages/ui/src/composables/useModalLevel.ts (hunk 8 above)
Comment (Azgiliat) [reply packages/ui/src/composables/useModalLevel.ts]: Changed

File: packages/ui/src/composables/useTrapFocus.ts (hunk 2 above)
Comment (Azgiliat) [reply packages/ui/src/composables/useTrapFocus.ts]: You are right with `nextTick` outside `trapFocus` 

We need `nextTick` because `trapFocus` works with DOM, so we must be sure that DOM has been updated after modal opened

File: packages/ui/src/components/va-modal/VaModal.vue (hunk 7 above)
Comment (Azgiliat) [reply packages/ui/src/components/va-modal/VaModal.vue]: Moved to it's own `wathcEffect`

**Review by m0ksem — APPROVED** [review]

**Review by asvae — APPROVED** [review]
Nice! 🤪
