### PR TITLE
fix: add html min and max attributes support

### LINKED ISSUE #2999: maxLength doesnt work in VaInput
https://discord.com/channels/457593300799717377/771405157527191585/1073687130955600072

### PR DESCRIPTION
**Pull request by rustem-nasyrov**
Close #2999

image

## Description
- Added `minlength` and `maxlength` attributes support.
- Added supported html attributes example.

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Improvement/refactoring (non-breaking change that doesn't add any feature but make things better)

### CODE REVIEW

File: packages/docs/page-config/ui-elements/input/examples/HtmlAttributes.vue [hunk 1]
```diff
@@ -0,0 +1,51 @@
+<template>
+  <div style="max-width: 300px">
+    <va-input
+      v-model="value"
+      type="password"
```
Comment (m0ksem) [inline packages/docs/page-config/ui-elements/input/examples/HtmlAttributes.vue:5]:
```suggestion
      type="password"
      label="type: password"
```

**Review by m0ksem — CHANGES_REQUESTED** [review]

**Comment by rustem-nasyrov** [comment]
@m0ksem,
image

**Comment by asvae** [comment]
image
