### PR TITLE
[#3362] Sidebar on mobile

### LINKED ISSUE #3362: Navigation bar shown by default on mobile
**Vuestic-ui version:** 1.6.4
Screenshot_2023-04-22-00-37-10-99_40deb401b9ffe8e1df2f1cc5ba480b12

**Steps to reproduce**

**What is the expected behavior?**

Navigation bar should not cover content

**What is the current behavior?**

**Other information**

Please check all screen sizes

### PR DESCRIPTION
**Pull request by RVitaly1978**
## Description
close #3362

<details>

https://user-images.githubusercontent.com/55198465/235647320-16f4ae11-6292-49d7-8a81-ba50ae506e7c.mov

</details>

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any feature but make things better)

### CODE REVIEW

**Review by m0ksem — CHANGES_REQUESTED** [review]
Makes it always hidden for me... We need maybe use local storage or cookie to show/hide sidebar.

**Review by misterpekert — CHANGES_REQUESTED** [review]
The buttons to toggle sidebar and menu header are not clickable for me. Always hidden and seems that smth is broken :(

File: packages/docs/components/layout/header/HeaderSelector.vue [hunk 1]
```diff
@@ -39,7 +39,7 @@ export default defineComponent({
   props: {
     minimized: {
       type: Boolean,
-      required: true,
+      default: false,
```
Comment (m0ksem) [inline packages/docs/components/layout/header/HeaderSelector.vue:42]: I think we 100% need this to be required, so we handle if sibebar can be toggled. It will be a bug to have this always default to false. If you want this flexable, you can change default to `undefined` and hide the whole button. We don't need this level of flexibility, so this prop must be required.

**Review by m0ksem — APPROVED** [review]
