### PR TITLE
Fix: va-rating-issues

### LINKED ISSUE #1952: `VaRating` disabled, readonly, hover behaviour
**Vuestic-ui version:** 1.4.1

**Steps to reproduce**
  - http://vuestic-ui-demo.sub.asva.by/#/demo/va-rating/VaRating.demo.vue
  - http://vuestic-ui-demo.sub.asva.by/#/demo/va-rating/components/VaRatingItem/VaRatingItem.demo.vue

**What is the current behavior?**
  - `disabled` and `readonly` weird behaviour
chrome-capture-2022-5-16

  - hover with `halves`
https://user-images.githubusercontent.com/55198465/174083141-30a98911-82d0-415e-86c4-b0d1e7982c89.mov

### PR DESCRIPTION
**Pull request by smellyshovel**
Closes #1952 

2 points.

1. Disabled and readonly props must take precedance over the `hover` prop. In other words, the component must not change its visual appearance when hovered in cases when it's either disabled or readonly.

Before:
https://user-images.githubusercontent.com/9782236/175301383-cf3f6c59-3481-474e-9cc6-f1752b8974de.mp4

After:
https://user-images.githubusercontent.com/9782236/175301614-d0cde0d0-49f0-4eca-8b4a-363f285c5838.mp4

2. **UPDATED - not a bug in the component, rather an improperly used demo. Reverted the fix.**

The hover-hitbox for a rating-item is somewhat corrupted. Modified it so that all the calculations happen in the context of the rating-item itself, not the wrapper. LGTM

Before:
https://user-images.githubusercontent.com/9782236/175302180-917ad9ad-bd33-44a0-bb63-694a045bad9e.mp4

After:
https://user-images.githubusercontent.com/9782236/175302056-b9552b2b-d16b-426e-8251-d528ed8f7de6.mp4

And it also allows to widen the item's wrapper when needed.
https://user-images.githubusercontent.com/9782236/175302244-2fc8a5b1-5503-45ac-87d4-82200e01607c.mp4

### CODE REVIEW

File: packages/ui/src/components/va-rating/hooks/useRating.ts [hunk 1]
```diff
@@ -23,14 +24,13 @@ export const useRatingProps = {
   hover: { type: Boolean, default: false },
```
Comment (m0ksem) [inline packages/ui/src/components/va-rating/hooks/useRating.ts:24]:
```suggestion
  hover: { type: Boolean, default: false },
  ...useFormProps,
```

**Review by m0ksem — APPROVED** [review]
