### PR TITLE
Fix icons for codesandbox

### LINKED ISSUE #1122: Codesandbox doesn't support icons
Open this example is codesandbox: 
https://vuestic.dev/en/ui-elements/avatar#with-icons

vuestic.dev:
image

codesandbox:
image

Icons are not being loaded.
Probably easy fix.

- [ ] Bonus point for randomly checking ~10 other examples to run properly in codesandbox.

### PR DESCRIPTION
**Pull request by kushich**
closes #1122

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any feature but make things better)

### CODE REVIEW

File: packages/docs/src/components/DocsNavigation.vue [hunk 1]
```diff
@@ -106,7 +106,14 @@ app.mount("#app");
     '@vue/cli-plugin-babel/preset'
   ]
 }`
-      const html = '<div id="app"></div>'
+      const html = `<link rel="icon" href="<%= BASE_URL %>favicon.ico">
```
Comment (asvae) [inline packages/docs/src/components/DocsNavigation.vue:109]: pretty sure BASE_URL won't be of any use :)

**Comment by asvae** [comment]
Thanks! Merge after fix.

**Review by asvae — APPROVED** [review]
