### PR TITLE
[#1761, #1739, #1898] Fix shallowRef and propType (part 3)

### LINKED ISSUE #1739: Make sure we use shallowRef instead of ref for DOM elements
```
const input = shallowRef<HTMLElement>()
```

Ref:
image

Shallow: 
image

First of all, shallowRef has higher performance. It also has a better typing, because Ref must Unwrap all object properties.

For me, it caused a ts error on build.

### LINKED ISSUE #1761: Remove extra PropType<...>
Remove `PropType<boolean>` or `PropType<string>` etc, as vue derives type from `{type: String}`.

### LINKED ISSUE #1898: Change all Element prop types to HTMLElement

### PR DESCRIPTION
**Pull request by RVitaly1978**
## Description
close #1761
close #1739
close #1898

refactored components:
- [x] va-option-list
- [x] va-progress-circle
- [x] va-radio
- [x] va-rating
- [x] va-select
- [x] va-separator
- [x] va-sidebar
- [x] va-slider
- [x] va-spacer
- [x] va-switch
- [x] va-tabs
- [x] va-time-picker
- [x] va-time-input
- [x] va-toast
- [x] composables

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Improvement/refactoring (non-breaking change that doesn't add any feature but make things better)

### CODE REVIEW

File: packages/ui/src/components/va-rating/components/VaRatingItem/VaRatingItem.vue [hunk 1]
```diff
@@ -45,14 +48,15 @@ export default defineComponent({
     tabindex: { type: Number, default: 0 },
     disabled: { type: Boolean, default: false },
```
Comment (aluarius) [inline packages/ui/src/components/va-rating/components/VaRatingItem/VaRatingItem.vue:49]: Is it used anywhere?

**Review by aluarius — APPROVED** [review]

File: packages/ui/src/components/va-rating/components/VaRatingItem/VaRatingItem.vue (hunk 1 above)
Comment (RVitaly1978) [reply packages/ui/src/components/va-rating/components/VaRatingItem/VaRatingItem.vue:49]: yes:
image

File: packages/docs/src/page-configs/ui-elements/option-list/examples/WithComplexData.vue [hunk 2]
```diff
@@ -1,14 +1,12 @@
...
-      disabledBy="altDisabled"
-      :textBy="option => option.altText"
-    />
-    Selected: <pre> {{ listValue }} </pre>
-  </div>
+  <va-option-list
+    :options="options"
+    v-model="listValue"
+    valueBy="altValue"
+    disabledBy="altDisabled"
```
Comment (rustem-nasyrov) [inline packages/docs/src/page-configs/ui-elements/option-list/examples/WithComplexData.vue:6]: Aren't we using `kebab-case` notation for the components props?

File: packages/docs/src/page-configs/ui-elements/table/examples/Clickable.vue [hunk 3]
```diff
@@ -27,15 +27,17 @@
...
+
+export default defineComponent({
   data () {
     return {
       users: users.slice(0, 4),
     }
   },
-}
+})
 </script>
```
Comment (rustem-nasyrov) [inline packages/docs/src/page-configs/ui-elements/table/examples/Clickable.vue:41]: Is here a reason to write the component with typescript?

File: packages/docs/src/page-configs/ui-elements/table/examples/Default.vue [hunk 4]
```diff
@@ -27,15 +27,17 @@
...
+import { users } from 'vuestic-ui/src/data/Users'
+
+export default defineComponent({
   data () {
     return {
       users: users.slice(0, 4),
     }
   },
-}
+})
```
Comment (rustem-nasyrov) [inline packages/docs/src/page-configs/ui-elements/table/examples/Default.vue:40]: Same here and below.

File: packages/ui/src/components/va-time-input/VaTimeInput.demo.vue [hunk 5]
```diff
@@ -92,7 +92,7 @@
 </template>
 
 <script>
-import VaTimeInput from './VaTimeInput.vue'
+import { VaTimeInput } from './index'
```
Comment (rustem-nasyrov) [inline packages/ui/src/components/va-time-input/VaTimeInput.demo.vue:95]:
```suggestion
import { VaTimeInput } from './'
```

File: packages/ui/src/components/va-timeline/VaTimelineItem/VaTimelineItem.vue [hunk 6]
```diff
@@ -1,93 +1,62 @@
 <script>
-import { VaTimelineSeparator } from '../VaTimelineSeparator/index.ts'
 import { h } from 'vue'
 
-export const $root = 'va-timeline-item'
+import { extractComponentProps, filterComponentProps } from '../../../utils/child-props'
+
+import { VaTimelineSeparator } from '../VaTimelineSeparator'
+
+const componentName = 'va-timeline-item'
```
Comment (rustem-nasyrov) [inline packages/ui/src/components/va-timeline/VaTimelineItem/VaTimelineItem.vue:8]: Constants should be written on the uppercase snake-case.

File: packages/ui/src/components/va-timeline/VaTimelineSeparator/VaTimelineSeparator.vue [hunk 7]
```diff
@@ -1,69 +1,56 @@
 <script>
 import { h } from 'vue'
-import { useColors } from '../../../services/color-config/color-config.ts'
 
-const $root = 'va-timeline-separator'
+import { useColors } from '../../../composables/useColor'
+
+const componentName = 'va-timeline-separator'
```
Comment (rustem-nasyrov) [inline packages/ui/src/components/va-timeline/VaTimelineSeparator/VaTimelineSeparator.vue:6]: Same as above.

File: packages/ui/src/composables/useLoading.ts [hunk 8]
```diff
@@ -11,13 +9,13 @@ export type LoadingProps = {
...
+//   const hasLoading = true
 
-  return {
-    hasLoading,
-  }
-}
+//   return {
+//     hasLoading,
+//   }
+// }
```
Comment (rustem-nasyrov) [inline packages/ui/src/composables/useLoading.ts:21]: If someone uses it already, and we want to remove this method, maybe we need to throw the warning?

**Review by rustem-nasyrov — CHANGES_REQUESTED** [review]

**Review by m0ksem — APPROVED** [review]

File: packages/docs/src/page-configs/ui-elements/option-list/examples/WithComplexData.vue (hunk 2 above)
Comment (RVitaly1978) [reply packages/docs/src/page-configs/ui-elements/option-list/examples/WithComplexData.vue:6]: now, as I see it, we do not use this notation. But I think we need to do as recommended by the [vue style guide](https://vuejs.org/style-guide/rules-strongly-recommended.html#prop-name-casing).
I think we should do it in a separate issue

File: packages/docs/src/page-configs/ui-elements/table/examples/Clickable.vue (hunk 3 above)
Comment (RVitaly1978) [reply packages/docs/src/page-configs/ui-elements/table/examples/Clickable.vue:41]: otherwise my IDE shows ts errors

File: packages/ui/src/composables/useLoading.ts (hunk 8 above)
Comment (RVitaly1978) [reply packages/ui/src/composables/useLoading.ts:21]: I checked: this hook is not used anywhere

**Review by rustem-nasyrov — APPROVED** [review]
