### PR TITLE
[#2033] Fix `VaDropdown` font

### LINKED ISSUE #2033: Missing fonts for popovers
Popovers use some wierd fonts by default. My browser is configured to use sans- families for missing fonts by default, but it seems to me like popovers are configured for some reason to use serif- fonts by default. Please, check this one.
Screenshot_20220630_182901

### PR DESCRIPTION
**Pull request by RVitaly1978**
## Description
close #2033

changes:
- [x] set font to `va-dropdown__content-wrapper`
- [x] use hook `useBem`

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any feature but make things better)

### CODE REVIEW

**Review by rustem-nasyrov — APPROVED** [review]

File: packages/ui/src/components/va-dropdown/VaDropdown.vue [hunk 1]
```diff
@@ -85,9 +87,7 @@ export default defineComponent({
       set (val) { statefulVal.value = val },
     })
 
-    const computedClass = computed(() => ({
-      'va-dropdown--disabled': props.disabled,
-    }))
+    const computedClass = useBem('va-dropdown', pick(props, ['disabled']))
```
Comment (m0ksem) [inline packages/ui/src/components/va-dropdown/VaDropdown.vue:90]: How does this reactive? We likely losing reactivity here by passing props value, instead of reference. This must be computed or () => pick(

We also need to double check for this issue in other usages.

**Review by m0ksem — CHANGES_REQUESTED** [review]

**Review by aluarius — APPROVED** [review]
