### PR TITLE
fix sort in datatable. fix sort in example

### LINKED ISSUE #398: Bug DataTable with sorting number and booleans
1. Sorting doesn't work with Numbers
2. Sorting doesn't work with Booleans
bug

### PR DESCRIPTION
**Pull request by m1mzz**
fix #398

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any feature but make things better)

### CODE REVIEW

File: packages/ui/src/components/vuestic-components/va-data-table/VaDataTableCustomDataManagerExample.vue [hunk 1]
```diff
@@ -16,6 +16,10 @@ import Vue from 'vue'
 import { Component } from 'vue-property-decorator'
 import users from '../../../data/users.json'
 import VaDataTable from './VaDataTable.vue'
+const transformToString = (a: any = '') => {
+  if (a === 'string') { return a }
```
Comment (untael) [inline packages/ui/src/components/vuestic-components/va-data-table/VaDataTableCustomDataManagerExample.vue:20]: typeof a?

Comment (m1mzz) [reply packages/ui/src/components/vuestic-components/va-data-table/VaDataTableCustomDataManagerExample.vue]: fixed
