### PR TITLE
Fix: Overflow behaviour of VaCollapse

### LINKED ISSUE #3931: VaCollapse hides overflow by default
**Vuestic-ui version:** 1.8.0

My guess is that collapse should always have scroll in this case. Otherwise that might be a surprise for user - at one element size - everything is working fine. At another - right part disappears into nowhere.

image

### PR DESCRIPTION
**Pull request by keerthanak-tw**
closes #3931 

Fix overflow behaviour of VaCollapse
## Description

The VaCollapse body wrapper had a overflow hidden which would have been causing the extra content to be clipped. Changed the overflow behaviour to auto so that users will get a scrollbar when the size exceeds more than allotted.
## Markup:

<details>

```vue
&__body-wrapper {
    transition: var(--va-collapse-body-wrapper-transition);
    overflow: scroll;   // Changed this to scroll from hidden

    &--bordered {
      border-bottom: 1px solid var(--va-background-border);

      .va-collapse--colored-header:not(.va-collapse--expanded) & {
        border-bottom: none;
      }

      .va-collapse--colored-body.va-collapse--expanded & {
        border-bottom: none;
      }
    }
  }
```
</details>

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Improvement/refactoring (non-breaking change that doesn't add any feature but make things better)

### CODE REVIEW

File: packages/ui/src/components/va-collapse/VaCollapse.vue [hunk 1]
```diff
@@ -224,7 +224,7 @@ export default defineComponent({
 
   &__body-wrapper {
     transition: var(--va-collapse-body-wrapper-transition);
-    overflow: hidden;
+    overflow: scroll;
```
Comment (m0ksem) [inline packages/ui/src/components/va-collapse/VaCollapse.vue:227]:
```suggestion
    overflow: auto;
```

> My guess is that collapse should always have scroll in this case

I think it meant that it must have scroll in case of overflow.

Comment (keerthanak-tw) [reply packages/ui/src/components/va-collapse/VaCollapse.vue]: That makes sense.. Applied the suggestion :)

**Review by m0ksem — APPROVED** [review]

**Comment by m0ksem** [comment]
@asvae, I added new story about collapse overflow, if you think it needs some changes, please, make a separate issue.
