### PR TITLE
Fix#1493 Fix `VaDataTable` selection behavior, add `sticky-header`

### LINKED ISSUE #1492: [va-datatable] should support fixed header which AG grid supported
**Vuestic-ui version:** 1.3.4

### LINKED ISSUE #1493: va-data-tabel loose selected items on filtering, when those are not in the result
**Vuestic-ui version:** 1.3.4

**Steps to reproduce**
go to https://vuestic.dev/en/ui-elements/data-table#pagination

Pagination example has selection and filter too:

at the example for pagination select on and filter for a different line (e.g. select Antonette and  type "Sam" in the filter field)
you will loose the selection BUT you wont loose selection if you type "Ant" - so the behaviour isn't really be intended, or is it?

**What is the expected behavior?**
selected items is a v-model array and should be manipulated via script only 

on filtering, selected item should stay selected, please!

**What is the current behavior?**
selection of item, that are not in the filtered result are lost

**Other information**
Peek 2022-02-09 10-32
Peek 2022-02-09 10-33

### PR DESCRIPTION
**Pull request by RVitaly1978**
## Description
close #1492
close #1493

changes:
- [x] update selectable behavior
- [x] add sticky-header behavior
- [x] update demo and docs examples

chrome-capture
chrome-capture (1)
chrome-capture

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any feature but make things better)

### CODE REVIEW

File: packages/ui/src/components/va-data-table/hooks/useColumns.ts [hunk 1]
```diff
@@ -71,25 +31,22 @@ export const buildTableColumn = (source: TTableColumnSource, initialIndex: numbe
...
-const buildColumnsFromItems = (rawItems: Ref<ITableItem[]>) => {
-  return Object.keys(merge({}, ...rawItems.value)).map(buildTableColumn)
+const buildColumnsFromItems = (items: Ref<ITableItem[]>) => {
+  return Object.keys(merge({}, ...items.value)).map(buildTableColumn)
 }
 
-const buildNormalizedColumns = (rawColumns: Ref<TTableColumnSource[]>) => {
-  return rawColumns.value.map(buildTableColumn)
+const buildNormalizedColumns = (columns: Ref<TTableColumnSource[]>) => {
+  return columns.value.map(buildTableColumn)
```
Comment (m0ksem) [inline packages/ui/src/components/va-data-table/hooks/useColumns.ts:39]:
```suggestion
const buildNormalizedColumns = (columns: TTableColumnSource[]) => {
  return columns.map(buildTableColumn)
```

How about remove Ref from these methods. This will remove overwhelming `toRef`.

File: packages/ui/src/components/va-data-table/VaDataTable.vue [hunk 2]
```diff
@@ -252,100 +293,38 @@ export default defineComponent({
...
-    },
-    striped: {
-      type: Boolean,
-      default: false,
-    },
+    columns: { type: Array as PropType<TTableColumnSource[]>, default: () => [] as TTableColumnSource[] },
+    items: { type: Array as PropType<ITableItem[]>, default: () => [] as ITableItem[] },
+    modelValue: { type: Array as PropType<ITableItem[]> }, // selectedItems
+    sortingOrder: { type: String as PropType<TSortingOrder> }, // model-able
+    sortBy: { type: String as PropType<string> }, // model-able
```
Comment (m0ksem) [inline packages/ui/src/components/va-data-table/VaDataTable.vue:303]: This must work without PropType...

**Review by m0ksem — CHANGES_REQUESTED** [review]
How about a sticky header demo? Would be nice to have different PRs for bug fixes and new features.

File: packages/ui/src/components/va-data-table/hooks/useColumns.ts (hunk 1 above)
Comment (RVitaly1978) [reply packages/ui/src/components/va-data-table/hooks/useColumns.ts]: done

File: packages/ui/src/components/va-data-table/VaDataTable.vue (hunk 2 above)
Comment (RVitaly1978) [reply packages/ui/src/components/va-data-table/VaDataTable.vue]: done

File: packages/ui/src/components/va-data-table/VaDataTable.vue [hunk 3]
```diff
@@ -429,6 +430,7 @@ export default defineComponent({
 
   &--sticky {
     overflow-y: auto;
+    height: var(--sticky-table-height);
```
Comment (m0ksem) [inline packages/ui/src/components/va-data-table/VaDataTable.vue:433]: Can't we set height if the table is not sticky? 🤔

**Review by m0ksem — CHANGES_REQUESTED** [review]

File: packages/ui/src/components/va-data-table/VaDataTable.vue (hunk 3 above)
Comment (RVitaly1978) [reply packages/ui/src/components/va-data-table/VaDataTable.vue]: Added

**Review by m0ksem — APPROVED** [review]
