### PR TITLE
Fix#882 Fix dateInput paddings

### LINKED ISSUE #822: Button cannot be clicked outside content
image

### PR DESCRIPTION
**Pull request by zvenigorodskaia**
## Description

close #822

Added width:100% to .va-dropdown class

Before:
image

After:
image

## Types of changes
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ]  New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any feature but make things better)

### CODE REVIEW

File: packages/ui/src/components/va-dropdown/VaDropdown.vue [hunk 1]
```diff
@@ -296,4 +296,8 @@ export default class VaDropdown extends mixins(
     z-index: var(--va-dropdown-content-wrapper-z-index);
   }
 }
+
+.va-dropdown:not(.va-popover) {
```
Comment (asvae) [inline packages/ui/src/components/va-dropdown/VaDropdown.vue:300]: If you want to create and exception for popover (dropdown width shouldn't be 100%), then it's better to be done in context of Popover, as dropdown is Popover dependency.
Dropdown shoudn't even know about Popover existance.

File: packages/ui/src/components/va-dropdown/VaDropdown.vue [hunk 2]
```diff
@@ -296,4 +296,8 @@ export default class VaDropdown extends mixins(
     z-index: var(--va-dropdown-content-wrapper-z-index);
```
Comment (asvae) [inline packages/ui/src/components/va-dropdown/VaDropdown.vue:296]: Button dropdown looks kinda broken :).

http://localhost:8080/#/demo/va-button-dropdown/VaButtonDropdown.demo.vue

**Comment by asvae** [comment]
Looks good. Thanks!
