### PR TITLE
Fix incorrectly applied progress bar height (#1950)

### LINKED ISSUE #1950: `VaProgressBar` with not large size and slot
**Vuestic-ui version:** 1.4.1

**Steps to reproduce**
  - https://vuestic.dev/en/ui-elements/progress-bar#slots

**What is the expected behavior?**
  - the slot should be visible when using the default size
  - the progress bar should have the correct height

**What is the current behavior?**

https://user-images.githubusercontent.com/55198465/174010950-91b2b97c-4dba-4b81-81ba-71f7228f5af2.mov

### PR DESCRIPTION
**Pull request by smellyshovel**
Resolves #1950 

What it used to look like:
image

What it looks like with the fix applied:
image

The issue was in that the `height` was applied to the whole block (including the slotted content) whereas it should be applied only to the progress bar's wrapper.

### CODE REVIEW

File: packages/ui/src/components/va-progress-bar/VaProgressBar.vue [hunk 1]
```diff
@@ -68,10 +67,13 @@ export default defineComponent({
       rootClass: computed(() => ({
         'va-progress-bar': true,
         'va-progress-bar--square': !props.rounded,
+      })),
+
+      wrapperClass: computed(() => ({
         [`va-progress-bar--${props.size}`]: isTextSize.value,
       })),
```
Comment (RVitaly1978) [inline packages/ui/src/components/va-progress-bar/VaProgressBar.vue:74]: this class must be in the root wrapper

**Review by RVitaly1978 — CHANGES_REQUESTED** [review]

File: packages/ui/src/components/va-progress-bar/VaProgressBar.vue (hunk 1 above)
Comment (smellyshovel) [reply packages/ui/src/components/va-progress-bar/VaProgressBar.vue:74]: Fair point, will be addressed.

Comment (smellyshovel) [reply packages/ui/src/components/va-progress-bar/VaProgressBar.vue]: Resolved via 96f8f5e

**Review by RVitaly1978 — APPROVED** [review]

**Review by m0ksem — APPROVED** [review]
