### PR TITLE
Fix/va-data-table pagination

### LINKED ISSUE #359: Return to current pagination number?
I'm trying to make a button that when returning to the form (edit) it goes back to the page number where that record was.

I tried to manipulate this.$refs.table.inputPage() but failed.

Someone could help me with this, as I have a few days with this problem.

this is my code:
https://gist.github.com/phpricardo/5734d1dd161da12f992e7113a371f025

If you need any more details just talk please.

### LINKED ISSUE #372: VDataTable pagination bugs
1. Pagination doesn't work with VDataTable
95x7hs8

2. Focus remains on the button after last page on list is selected
2w3Xwi2
3. Page do not reset to 1 after we apply sort
4. When the call to an API rest is modified by setting the page number, the paging component is not refreshed, even though the data is fetched correctly.

### PR DESCRIPTION
**Pull request by untael**
Closes #372, #211. Should closes #359 
## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Improvement/refactoring (non-breaking change that doesn't add any feature but make things better)

### CODE REVIEW

File: packages/ui/src/components/vuestic-components/va-data-table/VaDataTableCustomDataManagerExample.vue [hunk 1]
```diff
@@ -6,88 +6,99 @@
...
-        return this.users
-      }
 
-      return this.users.filter(user => {
-        return user.firstName.toLowerCase().startsWith(this.term.toLowerCase())
-      })
-    },
-  },
-  methods: {
-    sortAsc (items, field) {
```
Comment (untael) [inline packages/ui/src/components/vuestic-components/va-data-table/VaDataTableCustomDataManagerExample.vue:53]: reverted in d5a401d

File: packages/ui/src/components/vuestic-components/va-data-table/VaDataTableCustomDataManagerExample.vue [hunk 2]
```diff
@@ -6,88 +6,99 @@
...
-      return items.slice().sort((a, b) => {
-        return a[field].split('').reverse().join('').localeCompare(b[field].split('').reverse().join(''))
-      })
-    },
-    sortDesc (items, field) {
```
Comment (untael) [inline packages/ui/src/components/vuestic-components/va-data-table/VaDataTableCustomDataManagerExample.vue:58]: reverted in d5a401d
