### PR TITLE
[#1781] Fix: docs sidebar active route determination

### LINKED ISSUE #1781: Sidebar in docs must use strict check for paths.
image

### PR DESCRIPTION
**Pull request by dnischeta**
closes #1781 

## Description
Strict check that current path ends with a route name.

### Changes
- [x] condition for sidebar route to be active

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any feature but make things better)

### CODE REVIEW

**Review by RVitaly1978 — APPROVED** [review]

File: packages/docs/src/components/sidebar/Sidebar.vue [hunk 1]
```diff
@@ -107,7 +107,7 @@ export default defineComponent({
     }
 
     const routeHasActiveChild = (section: NavigationRoute) => {
-      return section.children?.some(({ name }) => route.path.endsWith(name))
+      return section.children?.some(({ name }) => route.path.endsWith(`/${name}`))
     }
```
Comment (rustem-nasyrov) [inline packages/docs/src/components/sidebar/Sidebar.vue:111]: Let'is simplify it:
```suggestion
    const routeHasActiveChild = (section: NavigationRoute) => section.children?.some(({ name }) => route.path.endsWith(`/${name}`))
```

Comment (dnischeta) [reply packages/docs/src/components/sidebar/Sidebar.vue]: Ok, done :)

**Review by aluarius — APPROVED** [review]
