### PR TITLE
[#2163] Fix `VaInputWrapper` `min-width`

### LINKED ISSUE #2163: Issue to set `min-width` and `width` rules to `VaInput`, `VaSelect`, `VaTimePicker`, `VaDatePicker`
**Vuestic-ui version:** 1.4.7

This not works:
```ts
<va-input style="min-width: 150px; width: 100%" />
<va-select style="min-width: 150px; width: 100%" />
<va-time-input style="min-width: 150px; width: 100%" />
<va-date-input style="min-width: 150px; width: 100%" />
```

### PR DESCRIPTION
**Pull request by RVitaly1978**
## Description
close #2163 

changes:
- [x] add global css-variable for the form-elements `min-width`
- [x] update `min-width` rule for components
- [x] change `display: flex` with `display: inline-block` for the `va-date-input` (according to other "input" components)

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any feature but make things better)

### CODE REVIEW

**Review by rustem-nasyrov — APPROVED** [review]

File: packages/ui/src/components/va-time-input/VaTimeInput.vue [hunk 1]
```diff
@@ -78,7 +79,6 @@
           <va-icon
             v-else-if="!$props.leftIcon"
             role="button"
-            class="va-dropdown__icons__reset"
```
Comment (aluarius) [inline packages/ui/src/components/va-time-input/VaTimeInput.vue:81]: Won't it remove focus-outline state?

**Review by aluarius — APPROVED** [review]

File: packages/ui/src/components/va-time-input/VaTimeInput.vue (hunk 1 above)
Comment (RVitaly1978) [reply packages/ui/src/components/va-time-input/VaTimeInput.vue:81]: This state sets in `va-icon` component:
```ts
.va-icon {
  vertical-align: var(--va-icon-vertical-align);
  user-select: var(--va-icon-user-select);

  &[tabindex]:not([tabindex^="-"]) {
    &:focus {
      @include focus-outline;
    }
  }

  ...
```

**Review by m0ksem — CHANGES_REQUESTED** [review]
I think we better remove min-width completely and use size of icons and subtract it from input-wrapper width. This way we can achieve removing jumping while validation icons are added to input, so input is not become bigger.  That would be a different task and different PR I think.

240px just sucks in practice.
