### PR TITLE
fix: #844 don't use <a> for collapse custom headers in docs' sidebar

### LINKED ISSUE #844: Sidebar items (expands) for the docs require 2 tab-presses before focused
Now we need to press the tab key an additional time to focus next sidebar item (docs). Should be a single press.

Leftover from #828

### PR DESCRIPTION
**Pull request by smellyshovel**
closes #844 

This also fixes the keyboard-tab'ing issue.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any feature but make things better)

### CODE REVIEW

**Comment by smellyshovel** [comment]
#844

**Review by asvae — COMMENTED** [review]
Perfect, thanks!

File: packages/docs/src/components/sidebar/Sidebar.vue [hunk 1]
```diff
@@ -7,15 +7,17 @@
...
-          <va-sidebar-item :activeColor="activeColor" @keydown.stop>
-            <va-sidebar-item-content :class="{ 'va-sidebar-item--active': isRouteHasActiveChild(route) }">
-              <va-sidebar-item-title>
-                {{ $t(route.displayName) }}
-              </va-sidebar-item-title>
-              <va-icon v-if="route.children" :name="value ? 'expand_less' : 'expand_more'" />
-            </va-sidebar-item-content>
-          </va-sidebar-item>
+        <template #header="{ value, hasKeyboardFocus }">
+          <div
```
Comment (m0ksem) [inline packages/docs/src/components/sidebar/Sidebar.vue:11]: It would be great if you fix the issue with the VaSidebarItem and VaCollapse components instead of removing them from the docs page.

image

There are two ways:
- Set tabindex -1 for <a> and react to VaCollapse focus
- Remove tabindex for VaCollapse header, to prevent extra focusing.

Comment (smellyshovel) [reply packages/docs/src/components/sidebar/Sidebar.vue:11]: The thing here is that, as per @asvae , there should be no links (anchors) at all inside the va-collapse's header (and it actually makes sense since we don't want to redirect the user somewhere - instead, we only want to open the collapse). And since the va-sidebar-item implys the use of links (it uses the `<a>` tag), I have to stop using the va-sidebar-item for collapse's header at all.

Here's how the new markup looks like:
Screenshot_20210614_182450

Comment (smellyshovel) [reply packages/docs/src/components/sidebar/Sidebar.vue:11]: And yep, the collapse's header itself still needs to be `tabindex`able to make it possible to open/close collapses using the keyboard.

Comment (asvae) [reply packages/docs/src/components/sidebar/Sidebar.vue:11]: @m0ksem I'm frankly not seeing any point jamming sidebar-item into collapse header. Outside of styling similarity it doesn't extend any of its behavior.

File: packages/docs/src/components/sidebar/Sidebar.vue [hunk 2]
```diff
@@ -7,15 +7,17 @@
...
+            class="sidebar__collapse-custom-header"
+            :class="{
+              'sidebar__collapse-custom-header--active': isRouteHasActiveChild(route),
+              'sidebar__collapse-custom-header--keyboard-focused': hasKeyboardFocus
+            }"
+          >
+            {{ $t(route.displayName) }}
+            <va-icon v-if="route.children" :name="value ? 'expand_less' : 'expand_more'" />
```
Comment (asvae) [inline packages/docs/src/components/sidebar/Sidebar.vue:19]:
```
v-if="route.children"
```
Can you check if this check is relevant? IMO if route doesn't have children - it shouldn't be collapse.

**Comment by asvae** [comment]
Thanks. Looks good.

**Review by asvae — APPROVED** [review]
