### PR TITLE
[#2037] Fix `VaTimeInput` `clearable` and `manual-input` behaviour

### LINKED ISSUE #2037: `VaTimePicker` cleanup icon does not disappear after cleaning
**Vuestic-ui version:** 1.4.4

chrome-capture-2022-6-1

### PR DESCRIPTION
**Pull request by RVitaly1978**
## Description
close #2037 

changes:
- [x] update `useClearable` and `canBeCleared` in the `va-time-input`
- [x] update `useTimeFormatter`
- [x] avoid opening dropdown if `manual-input` is enabled

chrome-capture-2022-6-5

chrome-capture-2022-6-5 (1)

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any feature but make things better)

### CODE REVIEW

**Review by rustem-nasyrov — APPROVED** [review]

File: packages/ui/src/components/va-time-input/VaTimeInput.vue [hunk 1]
```diff
@@ -161,47 +146,47 @@ export default defineComponent({
...
 
-    const valueText = computed<string | undefined>(() => {
-      if (!isValid.value) { return props.clearValue ? format(props.clearValue) : '' }
-      if (!modelValueSync.value) { return props.clearValue ? format(props.clearValue) : '' }
-
-      if (props.format) { return format(modelValueSync.value) }
-
-      return format(modelValueSync.value)
-    })
+    const valueText = computed<string>(() => modelValueSync.value
```
Comment (aluarius) [inline packages/ui/src/components/va-time-input/VaTimeInput.vue:155]:
```suggestion
    const valueText = computed<string>(() => format(modelValueSync.value || props.clearValue)
```

**Review by aluarius — APPROVED** [review]

File: packages/ui/src/components/va-time-input/VaTimeInput.vue [hunk 2]
```diff
@@ -216,21 +201,19 @@ export default defineComponent({
...
-
     const {
       canBeCleared,
       clearIconProps,
       onFocus,
       onBlur,
     } = useClearable(props, valueText)
 
+    const canBeClearedComputed = computed(() => (
+      canBeCleared.value && valueText.value !== format(props.clearValue)
```
Comment (m0ksem) [inline packages/ui/src/components/va-time-input/VaTimeInput.vue:214]: I dislike how text field jump now.

**Review by m0ksem — APPROVED** [review]

File: packages/ui/src/components/va-time-input/VaTimeInput.vue (hunk 2 above)
Comment (RVitaly1978) [reply packages/ui/src/components/va-time-input/VaTimeInput.vue:212]: I opened a separate issue #2054
