### PR TITLE
[#1691] Fix `VaSlider` mobile behavior

### LINKED ISSUE #1691: VaSlider in a touch interface not working properly
Test [`VaSlider`](https://vuestic.dev/en/ui-elements/slider)on mobile and laptop with touchscreen
Don't properly work [**vertical slider** ](https://vuestic.dev/en/ui-elements/slider#vertical) and [**Track label**](https://vuestic.dev/en/ui-elements/slider#track-label)-  cannot be dragged only picked
When u try drag down vertical slider on mobile - page refresh

### PR DESCRIPTION
**Pull request by RVitaly1978**
## Description
close #1691 

changes:
- [x] add `event.preventDefault` to prevent page scrolling
- [x] tweak moving dots with keyboard
- [x] update examples

https://user-images.githubusercontent.com/55198465/165296425-33469a7e-fd82-40bd-8039-7fe52c95f876.mov

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any feature but make things better)

### CODE REVIEW

File: packages/ui/src/components/va-slider/VaSlider.vue [hunk 1]
```diff
@@ -62,8 +62,8 @@
           class="va-slider__handler"
           :class="dotClass[order]"
           :style="dottedStyles[order]"
-          @mousedown="(moveStart($event, order), hasMouseDown = true)"
-          @touchstart="moveStart($event, order)"
+          @mousedown="moveStart($event, order), hasMouseDown = true"
```
Comment (m0ksem) [inline packages/ui/src/components/va-slider/VaSlider.vue:65]: Shouldn't we set `hasMouseDown` inside `moveStart`? Didn't we miss it here too?

https://github.com/epicmaxco/vuestic-ui/blob/fdc9fc4198a3cd8cc718e1a26414760c12e3945f/packages/ui/src/components/va-slider/VaSlider.vue#L96

**Review by m0ksem — APPROVED** [review]

File: packages/ui/src/components/va-slider/VaSlider.vue [hunk 2]
```diff
@@ -344,6 +344,8 @@ export default defineComponent({
     }
 
     const moveStart = (e: MouseEvent | TouchEvent, index = currentSliderDotIndex.value) => {
+      e.preventDefault() // prevent page scrolling
```
Comment (LighthouseKeeperYN) [inline packages/ui/src/components/va-slider/VaSlider.vue:347]: I'd use event modifier in template instead.

**Review by LighthouseKeeperYN — APPROVED** [review]

File: packages/ui/src/components/va-slider/VaSlider.vue (hunk 2 above)
Comment (m0ksem) [reply packages/ui/src/components/va-slider/VaSlider.vue:347]: Then you will need to add `.prevent` everywhere, where moveStart is used.

**Review by rustem-nasyrov — APPROVED** [review]

**Review by aluarius — APPROVED** [review]
