### PR TITLE
Fixed DOC's color palette and names.

### LINKED ISSUE #711: DOCS: Search placeholder color
Update search placeholder color to `secondary` which is `#767C88`.

### PR DESCRIPTION
**Pull request by DieselTripleX**
## Description

closes #711 

1. Fixed placeholder color as intended.
2. Added new colors to DOC's themes and adjusted names.
3. Fixed cases when used old color names with new theme.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Improvement/refactoring (non-breaking change that doesn't add any feature but make things better)

### CODE REVIEW

File: packages/docs/src/components/sidebar/Sidebar.vue [hunk 1]
```diff
@@ -1,5 +1,5 @@
 <template>
-  <va-sidebar class="sidebar" v-model="visible" :width="sidebarWidth">
+  <va-sidebar class="sidebar" v-model="visible" color="background" :width="sidebarWidth">
```
Comment (m0ksem) [inline packages/docs/src/components/sidebar/Sidebar.vue:2]: If you set sidebar default color to the background you don't need to add this prop here.
```suggestion
  <va-sidebar class="sidebar" v-model="visible" :width="sidebarWidth">
```

File: packages/docs/src/examples/va-sidebar/Color.vue [hunk 2]
```diff
@@ -1,6 +1,6 @@
 <template>
   <div class="mb-4" style="height: 16rem; border: 2px solid var(--va-primary);">
-    <va-sidebar color="primary" text-color="secondary" minimizedWidth="64px" width="18rem">
+    <va-sidebar color="primary" text-color="white" minimizedWidth="64px" width="18rem">
       <va-sidebar-item>
```
Comment (m0ksem) [inline packages/docs/src/examples/va-sidebar/Color.vue:4]:
```suggestion
      <va-sidebar-item active-color="background">
```

The first sidebar item should also have an active-color prop, like other items. Hover color is relative to active color. You can check colored docs demos and see how different is hover color.

**Review by m0ksem — CHANGES_REQUESTED** [review]
