### PR TITLE
[#1940] Fixed filtering and sorting of `VaDataTable` when using `items` with nested objects

### LINKED ISSUE #1940: `VaDataTable`: sorting and filtering don't work with custom slots
**Vuestic-ui version:** 1.4.1

Sorting and filtering don't work if we have such a custom slot
```vue
<va-data-table :items="items" :columns="columns">
  <template #cell(address)="{ rowData }">{{ rowData.address.street }}</template>
</va-data-table>
```

### PR DESCRIPTION
**Pull request by RVitaly1978**
## Description
close #1940

changes:
- [x] add `name` key to `columns`
- [x] update `key` key in `columns`
- [x] update examples

chrome-capture-2022-5-23

chrome-capture-2022-5-23 (1)

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any feature but make things better)

### CODE REVIEW

File: packages/ui/src/components/va-data-table/hooks/useSortable.ts [hunk 1]
```diff
@@ -107,7 +107,7 @@ export default function useSortable (
   // Sets the clicked heading's column as a one to sort by and toggles the sorting order from "asc" to "desc" to `null`
   // (un-sorted) if the same column is clicked again or sets sorting order to "asc" if some other column is chosen.
   function toggleSorting (column: DataTableColumnInternal) {
-    if (column.key === sortBySync.value) {
+    if (column.name === sortBySync.value) {
```
Comment (smellyshovel) [inline packages/ui/src/components/va-data-table/hooks/useSortable.ts:110]: name is marked as optional. What if it's not provided? Why is `key` subtituted with `name` everywhere?

**Review by aluarius — APPROVED** [review]

File: packages/ui/src/components/va-data-table/hooks/useSortable.ts (hunk 1 above)
Comment (m0ksem) [reply packages/ui/src/components/va-data-table/hooks/useSortable.ts:110]: Here we have two types: column and internal column. Internal column means that it is a built column. If name is not provided, then key will be used.

File: packages/docs/src/page-configs/ui-elements/data-table/examples/Filtering.vue [hunk 2]
```diff
@@ -40,40 +40,115 @@ export default defineComponent({
         name: 'Leanne Graham',
         username: 'Bret',
         email: 'Sincere@april.biz',
+        address: {
```
Comment (m0ksem) [inline packages/docs/src/page-configs/ui-elements/data-table/examples/Filtering.vue:43]: Do we need this large amount of data? It is hard for user to read demo.

**Review by m0ksem — APPROVED** [review]
