### PR TITLE
fix(#4001): checkbox margins in array-value mode

### LINKED ISSUE #4001: VaCheckbox: incorrect margins in array-value mode
**Vuestic-ui version:** 1.8.3

**Steps to reproduce**
https://www.chromatic.com/test?appId=64d608ab34b67e621ab50cfd&id=65491aac0cb292254de33c3e
**What is the expected behavior?**
Missing margins between checkboxes. Make sure it also present in vertical mode. Add array-value-vertical story. Notice that if horizontal only horizontal margins must be used. Same for vertical.
**What is the current behavior?**
image
**Other information**

### PR DESCRIPTION
**Pull request by pradnyabhukan**
## Description

Added the missing margins between checkboxes in array-value story.
Added an array-value-vertical story, with the margins.

closes https://github.com/epicmaxco/vuestic-ui/issues/4001

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any feature but make things better)

### CODE REVIEW

File: packages/ui/src/components/va-checkbox/VaCheckbox.vue [hunk 1]
```diff
@@ -128,9 +129,13 @@ export default defineComponent({
         color: computedError.value ? getColor('danger') : (props.success ? getColor('success') : ''),
         padding: !props.label
           ? ''
-          : props.leftLabel
-            ? '0 0.5rem 0 0'
-            : '0 0 0 0.5rem',
+          : props.vertical
+            ? '0.3rem 0 0.3rem 0.5rem'
```
Comment (m0ksem) [inline packages/ui/src/components/va-checkbox/VaCheckbox.vue:133]: We will need to move these values to CSS variables under `_variables.scss`, so they can be configured.

**Review by m0ksem — APPROVED** [review]

**Comment by m0ksem** [comment]
Thanks!
