### PR TITLE
fix(input): add null to modelValue prop type declaration

### LINKED ISSUE #3859: model-value type problem in some components
**Vuestic-ui version:** 1.8.0

**Steps to reproduce**
Some components do not accept variables whose values ​​may be null as v-models

**What is the expected behavior?**

**What is the current behavior?**

**Other information**
image

### PR DESCRIPTION
**Pull request by untael**
Closes #3859

## Description
Allows to pass null as value to `VaInput` `modelValue` with no TS errors.
PR also includes small tweak of `useCleave` composable

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any feature but make things better)

### CODE REVIEW

File: packages/ui/src/components/va-input/hooks/useCleave.ts [hunk 1]
```diff
@@ -78,7 +78,7 @@ export const useCleave = (
       }
     }
 
-    return syncValue.value
+    return syncValue.value || ''
```
Comment (m0ksem) [inline packages/ui/src/components/va-input/hooks/useCleave.ts:81]: Expect number (0) to work correctly here.

```suggestion
    return syncValue.value ?? ''
```
