### PR TITLE
Feat/switch stateful fix

### LINKED ISSUE #281: Stateful switch doesn't work
image
http://localhost:8080/#/demo/vuestic-components/va-switch/VaSwitch.demo.vue

### PR DESCRIPTION
**Pull request by Kushich**
## Description
closes #281

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any feature but make things better)

### CODE REVIEW

File: packages/ui/src/components/vuestic-mixins/SelectableComponent/SelectableMixin.js [hunk 1]
```diff
@@ -73,21 +82,21 @@ export const SelectableMixin = {
         return
       }
       if (this.modelIsArray) {
-        if (!this.value) {
-          this.$emit('input', [this.c_arrayValue])
-        } else if (this.value.includes(this.c_arrayValue)) {
-          this.$emit('input', this.value.filter(option => option !== this.c_arrayValue))
+        if (!this.c_value) {
+          this.valueComputed = [this.c_arrayValue]
```
Comment (asvae) [inline packages/ui/src/components/vuestic-mixins/SelectableComponent/SelectableMixin.js:86]: Couple of things I want to point here and in some other places.

1) The way `valueComputed` and statefullness is intended to be used is that you don't use `c_value` at all! You always interact with `valueComputed` as well as perform checks on it.
But:
2) Array access + stateful makes no sense. So for array access we pretend `computedValue` does not exist and use `c_value` + emit input directly.

To surmise:
* for array access use `c_value`.
* otherwise use `valueComputed`

File: packages/ui/src/components/vuestic-components/va-switch/VaSwitch.spec.js [hunk 2]
```diff
@@ -0,0 +1,26 @@
+import Vue from 'vue'
+import { shallowMount } from '@vue/test-utils'
+import VaSwitch from './VaSwitch'
+
+import { ColorThemePlugin } from '../../../services/ColorThemePlugin'
```
Comment (asvae) [inline packages/ui/src/components/vuestic-components/va-switch/VaSwitch.spec.js:5]: Component should work without color theme plugin. Ideally we want to test without it.

File: packages/ui/src/components/vuestic-components/va-switch/VaSwitch.demo.vue [hunk 3]
```diff
@@ -166,7 +166,7 @@
     <VbCard title="Stateless switch without v-model">
```
Comment (asvae) [inline packages/ui/src/components/vuestic-components/va-switch/VaSwitch.demo.vue:166]: padding
image

File: packages/ui/src/components/vuestic-components/va-switch/VaSwitch.spec.js [hunk 4]
```diff
@@ -0,0 +1,22 @@
+import { shallowMount } from '@vue/test-utils'
```
Comment (asvae) [inline packages/ui/src/components/vuestic-components/va-switch/VaSwitch.spec.js:1]: Please add context test (see `VaRating.spec.js > is contextable component`)

File: packages/ui/src/components/vuestic-components/va-switch/VaSwitch.vue [hunk 5]
```diff
@@ -265,19 +255,46 @@ export default {
...
+      &__input-wrapper {
+        transform: translateX(100%);
+      }
+    }
+  }
+
+  &--error {
+    .va-switch {
+      &__label {
+        color: $theme-danger;
```
Comment (asvae) [inline packages/ui/src/components/vuestic-components/va-switch/VaSwitch.vue:283]: js color

File: packages/ui/src/components/vuestic-components/va-switch/VaSwitch.demo.vue (hunk 3 above)
Comment (asvae) [inline packages/ui/src/components/vuestic-components/va-switch/VaSwitch.demo.vue:166]: On keyboard navigation I was able to land focus on disabled switch. That should not be the case.
image

Comment (asvae) [inline packages/ui/src/components/vuestic-components/va-switch/VaSwitch.demo.vue:166]: Should have cursor pointer on label

File: packages/ui/src/components/vuestic-components/va-switch/VaSwitch.vue [hunk 6]
```diff
@@ -287,20 +304,57 @@ export default {
...
+      .va-switch--large#{&} {
+        border-radius: 1.25rem;
+      }
     }
   }
 
-  &__track-label {
+  #{&}__track-label {
     color: $white;
+    margin: auto 7px auto 33px;
```
Comment (asvae) [inline packages/ui/src/components/vuestic-components/va-switch/VaSwitch.vue:323]: can't we do rems?
Also in other places?
Ideally we want rems except for cases, where we can't do rems.

**Comment by asvae** [comment]
Looks good. Thanks.
