### PR TITLE
Fix/data table performance issue

### LINKED ISSUE #1699: Investigate `VaDataTable` performance issue
**Vuestic-ui version:** 1.4.0-alpha1

According to our community [feedback in discord](https://discord.com/channels/457593300799717377/771405157527191585/966626637988896788) VaDataTable filtering performance dropped by a large margin:

> WOW - sorry but the breathtaking Performance of the filtering with version 1.3.4 has totally crumbled! I hope you can get that speed up again?

Investigate what was the root of this issue.
It is worth starting from the recent updates of this component.

### PR DESCRIPTION
**Pull request by LighthouseKeeperYN**
Fixes animation and performance of data table filtering

close #1699

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any feature but make things better)

### CODE REVIEW

**Review by m0ksem — APPROVED** [review]

File: packages/ui/src/components/va-data-table/hooks/useAnimationName.ts [hunk 1]
```diff
@@ -0,0 +1,33 @@
+
+import { computed, Ref, ref, watch } from 'vue'
+import { TableRow } from '../types'
+
+interface useSelectableProps {
+  currentPage: number | undefined
+  animated: boolean
+}
+
+export default function usePaginatedRows (
```
Comment (RVitaly1978) [inline packages/ui/src/components/va-data-table/hooks/useAnimationName.ts:10]:
```suggestion
export default function usePaginatedRows(
```

**Review by RVitaly1978 — APPROVED** [review]

**Review by RVitaly1978 — APPROVED** [review]
