### PR TITLE
Fix#2821/nuxt color presets fix

### LINKED ISSUE #2821: Dark Theme on Nuxt 3
**Vuestic-ui version:** 1.5.3

**Steps to reproduce**
I just wrote the code for setting the theme to "dark" in the app.vue. It does make some of the components dark but not all, the base background color and va-input components are not affected. However, if I write the code for setting the theme to dark in some component in the /pages directory, the dark theme works fine and as expected in Hot Module Reload, but if I refresh the page, the base background color and va-input components aren't affected with the dark theme again.

**What is the expected behavior?**
All components in the app will turn "dark"

**What is the current behavior?**

**Other information**
Nuxt Version 3 (Stable)

### PR DESCRIPTION
**Pull request by m0ksem**
closes #2821
close https://github.com/epicmaxco/vuestic-ui/issues/2824

Need to double-check if issue is gone with this PR.

### CODE REVIEW

File: packages/nuxt/src/runtime/plugin.ts [hunk 1]
```diff
@@ -42,18 +42,19 @@ export default defineNuxtPlugin((nuxtApp) => {
...
-        htmlAttrs: {
-          style: renderCSSVariables()
-        }
-      }))
-    }
+    watchEffect(() => {
+      const colorConfig = getGlobalProperty(app, '$vaColorConfig')
+
+      if (colorConfig) {
+        const renderCSSVariables = colorConfig.renderCSSVariables
```
Comment (aluarius) [inline packages/nuxt/src/runtime/plugin.ts:49]: May be will be better to handle & re-render only changed-new colors from color config? In performance purpose.

**Review by aluarius — APPROVED** [review]

**Comment by aluarius** [comment]
`write about this behaviour in docs and hope people read them` - this isn't proceeded via this pr.

File: packages/nuxt/src/runtime/plugin.ts (hunk 1 above)
Comment (m0ksem) [reply packages/nuxt/src/runtime/plugin.ts:49]: I think it is a minor thing
