### PR TITLE
Feat/fix checkbox

### LINKED ISSUE #239: Fix checkbox type and role
- [ ] checkbox input should have type="checkbox"
- [ ] checkbox input should have role="checkbox"

This is not as straightforward as it seems at first. If you add these directly - look goes broken

image
becomes
image

So we want semantics without breaking existing component.

### PR DESCRIPTION
**Pull request by Kushich**
## Description
Closes #239

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any feature but make things better)

### CODE REVIEW

File: packages/ui/src/components/vuestic-components/va-checkbox/VaCheckbox.vue [hunk 1]
```diff
@@ -146,90 +145,52 @@ export default {
...
+      }
+    }
   }
 
-  &__content {
-    flex-direction: row;
+  &--error {
+    .va-checkbox {
+      &__square {
+        border-color: $theme-red;
```
Comment (asvae) [inline packages/ui/src/components/vuestic-components/va-checkbox/VaCheckbox.vue:190]: Should take color from theme - 'error'.
Same for selected.

File: packages/ui/src/components/vuestic-components/va-checkbox/VaCheckbox.vue [hunk 2]
```diff
@@ -149,87 +149,60 @@ export default {
...
   }
 
-  &__error-message-container {
-    flex: 0 0 100%;
-    margin-left: 0.3rem; // To fit with checkbox.
-  }
+  &--selected {
+    .va-checkbox {
+      &__square {
+        background-color: $vue-green;
```
Comment (asvae) [inline packages/ui/src/components/vuestic-components/va-checkbox/VaCheckbox.vue:189]: Same problem here. Should use js color

File: packages/ui/src/components/vuestic-components/va-checkbox/VaCheckbox.vue [hunk 3]
```diff
@@ -149,87 +149,60 @@ export default {
...
+      }
+    }
   }
 
-  &__content {
-    flex-direction: row;
+  &--error {
+    .va-checkbox {
+      &__square {
+        border-color: $theme-danger;
```
Comment (asvae) [inline packages/ui/src/components/vuestic-components/va-checkbox/VaCheckbox.vue:202]: and here

File: packages/ui/src/components/vuestic-components/va-checkbox/VaCheckbox.vue [hunk 4]
```diff
@@ -18,27 +18,32 @@
       @blur="onBlur"
```
Comment (asvae) [inline packages/ui/src/components/vuestic-components/va-checkbox/VaCheckbox.vue:18]: padding
image

**Comment by asvae** [comment]
Merge after fixes
