### PR TITLE
Fix: VaButtonDropdown class-style refactor & alignment fix

### LINKED ISSUE #368: VaButtonGroup/VaButtonDropdown can't handle button size
* **What is the expected behavior?**
Components have no size props

* **What is the current behavior?**
Components refers on large/small (boolean) props

* **Steps to reproduce, ideally also a screenshot or gif if it's a style issue**
Pass props into the components

* **Other information** 
Component should refers to size ('small', 'medium', 'large') prop like VaButton.

### PR DESCRIPTION
**Pull request by untael**
Closes #368, #152

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Improvement/refactoring (non-breaking change that doesn't add any feature but make things better)

### CODE REVIEW

File: packages/ui/src/components/vuestic-components/va-button-dropdown/VaButtonDropdown.vue [hunk 1]
```diff
@@ -1,166 +1,145 @@
...
+    return this.showDropdown ? resultedIcon : this.c_icon
+  }
+
+  get computedClass () {
     return {
-      visible: false,
+      'va-button-dropdown': true,
+      'va-button-dropdown--split': this.c_split,
+      [`va-button-dropdown--${this.c_size}`]: true,
     }
```
Comment (asvae) [inline packages/ui/src/components/vuestic-components/va-button-dropdown/VaButtonDropdown.vue:122]: Split into 2 classes with conditions. Generally we do not want to use string composition for css classes as that complicates search.

File: packages/ui/src/components/vuestic-components/va-dropdown/VaDropdown.vue [hunk 2]
```diff
@@ -22,9 +22,9 @@
         class="va-dropdown__anchor-width-container"
         :style="anchorWidthContainerStyles"
       >
-        <slot />
+        <slot/>
       </div>
-      <slot v-else />
+      <slot v-else/>
```
Comment (asvae) [inline packages/ui/src/components/vuestic-components/va-dropdown/VaDropdown.vue:27]: can you configure ide in a way so that it styles self closing tags the way they are now? Alsom can you check if linter can autofix these?

Comment (untael) [reply packages/ui/src/components/vuestic-components/va-dropdown/VaDropdown.vue]: eslint config was extended
