### PR TITLE
Fix/select value by with multiple

### LINKED ISSUE #1587: Doesn`t work value-by prop with multiple va-select element
**Vuestic-ui version:** 1.3.4

**Steps to reproduce**
Create va-select element with array of objects for options then make it multiple with value-by prop and specify what value from options object return
https://codesandbox.io/s/amazing-goldwasser-557ndl?file=/src/App.vue
**What is the expected behavior?**
Return array of selected specified object property values in value-by
**What is the current behavior?**
Return array of selected options objects
**Other information**
For single select work as intendent

### PR DESCRIPTION
**Pull request by LighthouseKeeperYN**
close #1587

Multiple select with value-by prop now returns value-by value instead of entire object

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Improvement/refactoring (non-breaking change that doesn't add any feature but make things better)

### CODE REVIEW

File: packages/ui/src/components/va-select/VaSelect.vue [hunk 1]
```diff
@@ -309,8 +309,12 @@ export default defineComponent({
         return value
       },
 
-      set (value: any) {
-        emit('update:modelValue', getValue(value))
+      set (value: SelectableOption | SelectableOption[]) {
+        if (Array.isArray(value)) {
+          emit('update:modelValue', value.map(v => getValue(v)))
```
Comment (rustem-nasyrov) [inline packages/ui/src/components/va-select/VaSelect.vue:314]: If `getValue` doesn't accept any other arguments, you can just provide it as callback.

**Review by RVitaly1978 — APPROVED** [review]

**Review by m0ksem — APPROVED** [review]
You can ignore my suggestions 👍. Would be nice to have refactoring and bug fix in separated PRs.

**Review by rustem-nasyrov — APPROVED** [review]
