### PR TITLE
va-file-upload fixes + lint

### LINKED ISSUE #20: different file formats in VaFileUploadGalleryItem?
What about different file formats?
For example `tiff` comes to mind. Probably makes sense to do a small investigation on this.

_Originally posted by @asvae in https://github.com/epicmaxco/vuestic-ui/pull/10/threads/MDIzOlB1bGxSZXF1ZXN0UmV2aWV3VGhyZWFkMTk3OTkzMjE4OnYy/unresolve_

### PR DESCRIPTION
**Pull request by nastassiadanilova**
## Description

- After this [pr](https://github.com/epicmaxco/vuestic-ui/pull/86 ) it was impossible to call file upload dialogue by clicking a button. Fixed in this pr

- close #20 

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any feature but make things better)

### CODE REVIEW

File: src/components/vuestic-components/va-file-upload/VaFileUpload.vue [hunk 1]
```diff
@@ -14,6 +14,7 @@
         class="va-file-upload__field__button"
         :disabled="disabled"
         :color="colorComputed"
+        @click="callFileDialogue"
```
Comment (asvae) [inline src/components/vuestic-components/va-file-upload/VaFileUpload.vue]: What is this for? Doesn't seem to be needed on chrome.

**Comment by asvae** [comment]
Thank you!
