### PR TITLE
Fix #1846: useStateful works with modelValue

### LINKED ISSUE #1846: `Stateful` does not update from modelValue
**Vuestic-ui version:** 1.4.0

**Steps to reproduce**

1. Set `stateful` prop to `true`
2. Update `modelValue`
3. Stateful component will not get this update

**What is the expected behavior?**
`modelValue` should update component even if it `stateful`

### PR DESCRIPTION
**Pull request by Derranion**
## Description
Closes #1846

`useStateful` now works correctly with `modelValue` - previously `modelValue` updates were ignored completely.
</details>

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)

### CODE REVIEW

**Review by aluarius — APPROVED** [review]

**Review by rustem-nasyrov — APPROVED** [review]

File: packages/ui/src/composables/useStateful.ts [hunk 1]
```diff
@@ -29,6 +29,19 @@ export function useStateful<T, D extends T = T> (
...
+
+  const watchModelValue = () => {
+    unwatchModelValue = watch(modelValueRef, (modelValue) => {
+      valueState.value = modelValue
+    })
+  }
+
+  watch(statefulRef, (stateful: boolean) => {
+    stateful ? watchModelValue() : unwatchModelValue?.()
+  }, { immediate: true })
```
Comment (RVitaly1978) [inline packages/ui/src/composables/useStateful.ts:44]: Maybe it will work the same?
```suggestion
  watch([props.stateful, props.modelValue], ([stateful: boolean, modelValue: T]) => {
    if (stateful && modelValue !== undefined) {
      valueState.value = modelValue
    }
  }, { immediate: true })
```

**Review by RVitaly1978 — CHANGES_REQUESTED** [review]

File: packages/ui/src/composables/useStateful.ts (hunk 1 above)
Comment (Derranion) [reply packages/ui/src/composables/useStateful.ts:44]: This will never work because `props.stateful` and `props.modelValue` are not `refs`.

If we will make them `refs` to make it work there will be other issue - we will always watch for `modelValue` even when it is not needed.

Which is not optimal.

Comment (Derranion) [reply packages/ui/src/composables/useStateful.ts:44]: This will never work because props.stateful and props.modelValue are not refs.

If we will make them refs, to make it work, there will be other issue - we will always watch for modelValue even when it is not needed.

Which is not optimal.

Comment (RVitaly1978) [reply packages/ui/src/composables/useStateful.ts:44]: I updated my suggestion: replaced props with functions:
`watch([() => props.stateful, () => props.modelValue], ([stateful, modelValue]) => {...`

Comment (Derranion) [reply packages/ui/src/composables/useStateful.ts:44]: Ok then

"there will be other issue - we will always have additional watcher for modelValue in every component and change valueState twice when it is not needed.

Which is not optimal."

Comment (Derranion) [reply packages/ui/src/composables/useStateful.ts:44]: Ok then

"there will be other issue - we will always have additional watcher for modelValue in every component when it is not needed.

Which is not optimal."

Comment (RVitaly1978) [reply packages/ui/src/composables/useStateful.ts:44]: If there are no cases where `stateful` can change dynamically, we can do this:
```
if (props.stateful) {
  watch(() => props.modelValue, (modelValue) => {
    if (modelValue !== undefined) {
      valueState.value = modelValue
    }
  }, { immediate: true })
}
```
otherwise we can update your solution a bit:
```
let unwatchModelValue: Function

const watchModelValue = () => {
  unwatchModelValue = watch(() => props.modelValue, (modelValue) => {
    if (modelValue !== undefined) {
      valueState.value = modelValue
    }
  }, { immediate: true }) // to handle if passed defaultValue
}

watch(() => props.stateful, (stateful) => {
  stateful ? watchModelValue() : unwatchModelValue?.()
}, { immediate: true })
```

Comment (Derranion) [reply packages/ui/src/composables/useStateful.ts:44]: `Stateful` can be changed by the user any time.

`undefined` can be a valid `modelValue` in some cases.

Passed `defaultValue` is handled immediately here:
`  const valueState = ref(defaultValue === undefined ? props.modelValue : defaultValue) as Ref<T>`

I've moved `refs` to `functions` though, indeed slightly less verbose but less explicit as well.

**Review by RVitaly1978 — APPROVED** [review]
