### PR TITLE
Fix #1308 Fix VaInput textarea height and resize

### LINKED ISSUE #1308: Textarea's row limits don't work without an autogrow prop
**Vuestic-ui version:** 1.3.1

**Steps to reproduce**
Screenshot 2021-12-06 at 14 30 03
Screenshot 2021-12-06 at 14 30 14

**What is the expected behavior?**
Limits for rows without an autogrow prop.

### PR DESCRIPTION
**Pull request by RVitaly1978**
## Description
close: #1308 

Changes:
- [x] - fix textarea height
- [x] - update resize logic

chrome-capture

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any feature but make things better)

### CODE REVIEW

File: packages/ui/src/components/va-input/components/VaTextarea/VaTextarea.vue [hunk 1]
```diff
@@ -46,18 +48,22 @@ export default defineComponent({
...
+        rowHeight.value = calculateRowHeight()
+      }
     }
 
     const updateHeight = () => {
-      if (!props.autosize || !textarea.value) { return }
-
-      height.value = textarea.value?.scrollHeight || 0
+      if (isResizable.value) {
+        height.value = calculateHeight() || 0
```
Comment (m0ksem) [inline packages/ui/src/components/va-input/components/VaTextarea/VaTextarea.vue:65]: UnTG7PDWeP

Here is a bug in height calculation.

**Review by m0ksem — CHANGES_REQUESTED** [review]

File: packages/ui/src/components/va-input/components/VaTextarea/VaTextarea.vue [hunk 2]
```diff
@@ -82,10 +88,11 @@ export default defineComponent({
 
     return {
       textarea,
-      computedHeight: computed(() => ({
+      computedStyle: computed(() => ({
         minHeight: rowHeight.value * props.minRows + 'px',
-        maxHeight: rowHeight.value * props.maxRows + 'px',
+        maxHeight: props.maxRows && (rowHeight.value * props.maxRows + 'px'),
```
Comment (Derranion) [inline packages/ui/src/components/va-input/components/VaTextarea/VaTextarea.vue:93]: We can move logic away from `return`:

```
return {
  ...
  computedStyle,
  ...
}
```

File: packages/ui/src/components/va-input/components/VaTextarea/VaTextarea.vue [hunk 3]
```diff
@@ -82,10 +88,11 @@ export default defineComponent({
...
         height: height.value + 'px',
+        resize: props.autosize && 'none',
```
Comment (Derranion) [inline packages/ui/src/components/va-input/components/VaTextarea/VaTextarea.vue:95]: Would be great if you can add prop description to [our docs](https://vuestic.dev/en/ui-elements/input#api) as well.

**Review by Derranion — APPROVED** [review]

File: packages/ui/src/components/va-input/components/VaTextarea/VaTextarea.vue (hunk 2 above)
Comment (RVitaly1978) [reply packages/ui/src/components/va-input/components/VaTextarea/VaTextarea.vue:93]: fixed it

File: packages/ui/src/components/va-input/components/VaTextarea/VaTextarea.vue (hunk 3 above)
Comment (RVitaly1978) [reply packages/ui/src/components/va-input/components/VaTextarea/VaTextarea.vue:95]: Probably we have some problems with our doc app, because in translations we have this description:
Screenshot 2021-12-28 at 14 23 03

File: packages/ui/src/components/va-input/components/VaTextarea/VaTextarea.vue (hunk 1 above)
Comment (RVitaly1978) [reply packages/ui/src/components/va-input/components/VaTextarea/VaTextarea.vue]: fixed it

File: packages/ui/src/components/va-input/components/VaTextarea/VaTextarea.vue (hunk 3 above)
Comment (m0ksem) [reply packages/ui/src/components/va-input/components/VaTextarea/VaTextarea.vue]: @RVitaly1978, try to add `name: 'VaInput'` to component options. That should make a trick. 

Vue class component auto generates component name from its class. Define component not able to make that, so we need to provide component name manually. Would be great to have component name as ESLint rule.

**Review by m0ksem — APPROVED** [review]

File: packages/ui/src/components/va-input/components/VaTextarea/VaTextarea.vue (hunk 3 above)
Comment (RVitaly1978) [reply packages/ui/src/components/va-input/components/VaTextarea/VaTextarea.vue]: fixed it in `va-input` and its inner components
