### PR TITLE
[#2324] Fix `VaDataTable` inputs width in CRUD example

### LINKED ISSUE #2324: Data table inputs looks bad
Inputs must be 100%
https://vuestic.dev/en/ui-elements/data-table#other

Also you might change input min width to fit small cells:
Same for select
```scss
    .va-input, .va-select {
        --va-form-element-default-width: 80px;
        width: 100%;
    }
```

### PR DESCRIPTION
**Pull request by RVitaly1978**
## Description
close #2324 

changes:
- [x] tweak `va-input` components styles within table

chrome-capture-2022-8-12

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Improvement/refactoring (non-breaking change that doesn't add any feature but make things better)

### CODE REVIEW

**Review by aluarius — APPROVED** [review]

**Review by rustem-nasyrov — APPROVED** [review]

File: packages/docs/src/page-configs/ui-elements/data-table/examples/CRUD.vue [hunk 1]
```diff
@@ -138,11 +139,28 @@ export default defineComponent({
...
+  .table-example {
+    &__slot {
+      th {
+        padding-top: 5px;
+        padding-bottom: 5px;
+        vertical-align: middle;
+      }
+
+      .va-input {
+        --va-form-element-default-width: 80px;
```
Comment (m0ksem) [inline packages/docs/src/page-configs/ui-elements/data-table/examples/CRUD.vue:151]:
```suggestion
        --va-form-element-default-width: 0;
```

`va-form-element-default-width` can be set inside `va-data-table` component instead.

File: packages/docs/src/page-configs/ui-elements/data-table/examples/CRUD.vue [hunk 2]
```diff
@@ -138,11 +139,28 @@ export default defineComponent({
...
+
+        width: 100%;
```
Comment (m0ksem) [inline packages/docs/src/page-configs/ui-elements/data-table/examples/CRUD.vue:153]: Here we need to use some `d-block` css helper class like block or smth.
```suggestion
        display: block;
```

File: packages/docs/src/page-configs/ui-elements/data-table/examples/CRUD.vue [hunk 3]
```diff
@@ -138,11 +139,28 @@ export default defineComponent({
...
 <style lang="scss" scoped>
-  .table-example--slot {
-    th {
-      padding-top: 5px;
-      padding-bottom: 5px;
-      vertical-align: middle;
+  .table-example {
+    &__slot {
+      th {
+        padding-top: 5px;
```
Comment (m0ksem) [inline packages/docs/src/page-configs/ui-elements/data-table/examples/CRUD.vue:145]: Prefer `class="py-2"` I guess...

**Review by m0ksem — APPROVED** [review]
