### PR TITLE
VaTabs become broken after window resize

### LINKED ISSUE #773: VaTabs become broken after window resize
https://user-images.githubusercontent.com/23530004/118495025-71767f00-b72b-11eb-9779-db1d25d18a80.mp4

Tested on Firefox

### LINKED ISSUE #904: Va-Tabs pagination does not work correctly when changing the number of tabs
* **What is the expected behavior?**
The state of the arrows should update correctly when changing the number of tabs.

* **What is the current behavior?**
Va-Tabs pagination does not work correctly

https://user-images.githubusercontent.com/20461547/123796336-b5919d80-d8ed-11eb-8f74-aa5e6e5da454.mov

Tested in google chrome.
http://localhost:8080/#/demo/vuestic-components/va-tabs/VaTabs.demo.vue

### LINKED ISSUE #906: Grow tab on small screen size doesn't allow to select right tabs
image

Needs a bit of investigation on how to work this out.

### PR DESCRIPTION
**Pull request by sergey-kravcov**
close #773 
close #906 
close #904 

## Description
Refactoring va-tabs components.
Fixed some bugs related to window resizing and resizing of the va-tabs element:
- the right prop did not work on the small screen
- the center prop did not work on the small screen
-  the pagination did not work on the small screen
- the slider worked incorrect on the resizing window
- window resizing with selected the last tab worked incorrect
- window resizing without selected tab and  at the end position of the pagination worked incorrect
- the grow prop worked incorrect when resize window
- fixed Va-Tabs pagination when changing the number of tabs

https://user-images.githubusercontent.com/20461547/123774922-8de30b00-d8d6-11eb-884f-30cc1969610e.mov

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Improvement/refactoring (non-breaking change that doesn't add any feature but make things better)

### CODE REVIEW

File: packages/ui/src/components/vuestic-components/va-tabs/VaTab/VaTab.vue [hunk 1]
```diff
@@ -15,7 +15,7 @@
       class="va-tab__content"
```
Comment (asvae) [inline packages/ui/src/components/vuestic-components/va-tabs/VaTab/VaTab.vue:15]: Shouldn't have transition on mount.
image

File: packages/ui/src/components/vuestic-components/va-tabs/VaTab/VaTab.vue [hunk 2]
```diff
@@ -15,7 +15,7 @@
...
       v-on="context.keyboardFocusListeners"
```
Comment (asvae) [inline packages/ui/src/components/vuestic-components/va-tabs/VaTab/VaTab.vue:16]: Simplify default case a bit (move disabled to disabled tabs), icons to icons etc.
image

File: packages/ui/src/components/vuestic-components/va-tabs/VaTab/VaTab.vue [hunk 3]
```diff
@@ -15,7 +15,7 @@
...
       @focus="onFocus"
```
Comment (asvae) [inline packages/ui/src/components/vuestic-components/va-tabs/VaTab/VaTab.vue:17]: When you size down the window - tab title jumps right and left.
image

Not a huge deal. You can move to different issue or something.

File: packages/ui/src/components/vuestic-components/va-tabs/VaTab/VaTab.vue (hunk 2 above)
Comment (sergey-kravcov) [reply packages/ui/src/components/vuestic-components/va-tabs/VaTab/VaTab.vue:16]: Fixed it
Снимок экрана 2021-06-30 в 13 06 31

File: packages/ui/src/components/vuestic-components/va-tabs/VaTab/VaTab.vue (hunk 3 above)
Comment (sergey-kravcov) [reply packages/ui/src/components/vuestic-components/va-tabs/VaTab/VaTab.vue:17]: Fixed it. The bug occurred when there was only one tab in the tab container.

File: packages/ui/src/components/vuestic-components/va-tabs/VaTab/VaTab.vue (hunk 1 above)
Comment (sergey-kravcov) [reply packages/ui/src/components/vuestic-components/va-tabs/VaTab/VaTab.vue:15]: fixed it

File: packages/ui/src/components/vuestic-components/va-tabs/VaTab/VaTab.vue [hunk 4]
```diff
@@ -124,19 +116,17 @@ export default class VaTab extends mixins(
...
+  updateSidePositions () {
+    this.rightSidePosition = this.$el.offsetLeft + this.$el.offsetWidth
+    this.leftSidePosition = this.$el.offsetLeft
+  }
+
   beforeMount () {
-    // const idx = this.tabsHanler.tabs.push(this)
-    // this.id = (this as any).$props.name || idx
-    // eslint-disable-next-line no-unused-expressions
     this.context.tabsService?.register(this)
```
Comment (asvae) [inline packages/ui/src/components/vuestic-components/va-tabs/VaTab/VaTab.vue:125]: Tab should never work without tabsService, so that `?.` is dubious.

File: packages/ui/src/components/vuestic-components/va-tabs/VaTab/VaTab.vue [hunk 5]
```diff
@@ -124,19 +116,17 @@ export default class VaTab extends mixins(
...
   }
 
   beforeUnmount () {
-    // eslint-disable-next-line no-unused-expressions
     this.context.tabsService?.unregister(this)
```
Comment (asvae) [inline packages/ui/src/components/vuestic-components/va-tabs/VaTab/VaTab.vue:129]: Same here

File: packages/ui/src/components/vuestic-components/va-tabs/VaTabs.demo.vue [hunk 6]
```diff
@@ -378,14 +344,41 @@
       >
         <template #tabs>
           <va-tab
-            v-for="title in ['One', 'Two', 'Three', 'Four']"
```
Comment (asvae) [inline packages/ui/src/components/vuestic-components/va-tabs/VaTabs.demo.vue:381]: No need to move back, but generally it's fine to keep stuff like this in demos.
You don't really have to refactor these or change even.

Actually I would've preferred something like this:
```vue
<va-tab>One</va-tab>
<va-tab>Two</va-tab>
....
```
unless you're testing adding/removing tabs.

File: packages/ui/src/components/vuestic-components/va-tabs/VaTabs.vue [hunk 7]
```diff
@@ -14,7 +14,7 @@
         flat
         size="medium"
         :icon="$props.prevIcon"
-        @click="movePaginationLeft()"
```
Comment (asvae) [inline packages/ui/src/components/vuestic-components/va-tabs/VaTabs.vue:17]: It's preferable to keep brackets if you don't pass anything to method.
And remove them if you pass event.

File: packages/ui/src/components/vuestic-components/va-tabs/VaTabs.vue [hunk 8]
```diff
@@ -319,23 +333,48 @@ export default class VaTabs extends mixins(
     this.sliderHeight = 0
   }
 
-  mounted () {
-    window.addEventListener('resize', this.updateTabsState)
-    this.updateTabsState()
-    this.mutationObserver = new MutationObserver(() => {
+  updateStartingXPoint () {
+    this.startingXPoint = 0
```
Comment (asvae) [inline packages/ui/src/components/vuestic-components/va-tabs/VaTabs.vue:337]: Early return is nice :).

```ts
this.startingXPoint = 0
if (!this.showPagination) return
if (this.$props.right) {
  this.startingXPoint = this.tabsRef?.clientWidth - this.containerRef?.clientWidth
} else if (this.$props.center) {
  this.startingXPoint = Math.floor((this.tabsRef?.clientWidth - this.containerRef?.clientWidth) / 2)
}
```

File: packages/ui/src/components/vuestic-components/va-tabs/VaTab/VaTab.vue [hunk 9]
```diff
@@ -14,10 +14,10 @@
     <div
       class="va-tab__content"
       v-on="context.keyboardFocusListeners"
-      @focus="onFocus"
-      @click="onTabClick()"
-      @keydown.enter="onTabKeydown"
       :tabindex="tabIndexComputed"
+      @focus="onFocus()"
```
Comment (asvae) [inline packages/ui/src/components/vuestic-components/va-tabs/VaTab/VaTab.vue:18]: vertical tab 4 doesn't move slider
image

File: packages/ui/src/components/vuestic-components/va-tabs/VaTab/VaTab.vue [hunk 10]
```diff
@@ -14,10 +14,10 @@
...
+      @click="onTabClick()"
```
Comment (asvae) [inline packages/ui/src/components/vuestic-components/va-tabs/VaTab/VaTab.vue:19]: Sometimes clicking on item doesn't select item, just moves scroll.

File: packages/ui/src/components/vuestic-components/va-tabs/VaTab/VaTab.vue [hunk 11]
```diff
@@ -14,10 +14,10 @@
...
+      @keydown.enter="onTabKeydown()"
```
Comment (asvae) [inline packages/ui/src/components/vuestic-components/va-tabs/VaTab/VaTab.vue:20]: Adding one more tab shouldn't scroll the tab.

**Comment by asvae** [comment]
Thanks!
