### PR TITLE
fix: change default value for selectable props

### LINKED ISSUE #2572: [Select] value-by is invalid
```vue
  <va-select
        label="展示筛选器"
        v-model="selectedFilters"
        :options="[
          { title: 'aa', name: 'aa' },
          { title: 'bb', name: 'bb' },
        ]"
        text-by="title"
        value-by="name"
        multiple
      ></va-select>
const selectedFilters = ref<string[]>([])

```
https://user-images.githubusercontent.com/36926073/198000550-2be663cd-49f6-40d2-b46f-12b10d34952f.mov

by modify 
```vue

:options="[
          { title: 'aa',value: 'aa' },
          { title: 'bb', value: 'bb' },
        ]" 
value-by='value'

 ```
ths issue resolve 

```json
"vuestic-ui": "0.0.0-experimental-7568c8b61-20221019"
```

### PR DESCRIPTION
**Pull request by rustem-nasyrov**
Close #2572

## Description
- Updated default values for the props.
- Fixed test.
- 
## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)

### CODE REVIEW

File: packages/ui/src/composables/useSelectableList.ts [hunk 1]
```diff
@@ -9,8 +9,8 @@ type StringOrFunction = string | ((option: SelectableOption) => unknown)
 export const useSelectableListProps = {
   options: { type: Array as PropType<SelectableOption[]>, default: () => [] },
   textBy: { type: [String, Function] as PropType<StringOrFunction>, default: 'text' },
-  valueBy: { type: [String, Function] as PropType<StringOrFunction>, default: '' },
-  trackBy: { type: [String, Function] as PropType<StringOrFunction>, default: 'value' },
+  valueBy: { type: [String, Function] as PropType<StringOrFunction>, default: 'value' },
```
Comment (m0ksem) [inline packages/ui/src/composables/useSelectableList.ts:12]:
```suggestion
  valueBy: { type: [String, Function] as PropType<StringOrFunction>, default: '' },
```

Let's better have it as empty string. Because there is no way to get object as value, user will need to pass `:value-by="''"`

**Review by m0ksem — CHANGES_REQUESTED** [review]

**Review by m0ksem — APPROVED** [review]
