### PR TITLE
VaDataTable fixes

### LINKED ISSUE #2653: [va-data-table] can't use component at all
**Vuestic-ui version:** 1.5.0

**Steps to reproduce**

1. create a fresh vueJs project (`npm init vue@latest`)
2. install vuestic-ui (`vue add vuestic-ui`)
3. in `App.vue` add `import {VaDataTable} from 'vuestic-ui'` and then `<VaDataTable></VaDataTable>` component in the template

**What is the expected behavior?**

See a working data table

**What is the current behavior?**
Chrome Inspector returns 2 errors:
* `useIntersectionObserver.ts:30 Uncaught TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))`
* `VaDataTable.vue:524 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'selectedColor')`

### PR DESCRIPTION
**Pull request by rustem-nasyrov**
Close #2653

## Description
- Fixed `v-bind()` usage in styles.
- Fixed intersection observer for the table and its initialization.
- Other little fixes.

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Improvement/refactoring (non-breaking change that doesn't add any feature but make things better)

### CODE REVIEW

File: packages/ui/src/components/va-data-table/hooks/useTableScroll.ts [hunk 1]
```diff
@@ -51,7 +51,9 @@ export default function useTableScroll (
     rootMargin: `${props.scrollTopMargin ?? 0}px 0px ${props.scrollBottomMargin ?? 0}px 0px`,
   }))
 
-  useIntersectionObserver(intersectionHandler, options, targets)
+  onMounted(() => {
+    useIntersectionObserver(intersectionHandler, options, targets)
```
Comment (m0ksem) [inline packages/ui/src/components/va-data-table/hooks/useTableScroll.ts:55]: This is wrong. All composables must be used in scope of setup function, not mounted.

You will cause making things on each mount, which potentially can cause memory leaks. Especially with intersection observer, which must call disconnect method like destruxtor

File: packages/ui/src/composables/useEvent.ts [hunk 2]
```diff
@@ -28,12 +28,12 @@ export const useEvent = <N extends UseEventEventName, E extends Event>(
 
   watch(source, (newValue, oldValue) => {
     if (!Array.isArray(event)) {
-      unref(newValue)?.addEventListener(event, listener as any, capture)
-      unref(oldValue)?.removeEventListener(event, listener as any, capture)
+      unref(newValue)?.addEventListener?.(event, listener as any, capture)
```
Comment (m0ksem) [inline packages/ui/src/composables/useEvent.ts:31]: How is that possible for html element to not have addEventListener?

If this is vnode, you might need useHTMLElement to do vnode.$el

**Review by m0ksem — CHANGES_REQUESTED** [review]

File: packages/ui/src/composables/useEvent.ts (hunk 2 above)
Comment (rustem-nasyrov) [reply packages/ui/src/composables/useEvent.ts:31]: Because of this: 
image
