### PR TITLE
Fix #1226 Fix VaTimeInput bug when passed text is not valid

### LINKED ISSUE #1226: Timepicker breaks down after writing text
CU34Ef0

Also there is a question: should we have possibility to write text?

### PR DESCRIPTION
**Pull request by RVitaly1978**
## Description
close: #1226 

Changes:
- [x] - fix `va-time-input` bug when passed text (prop `manual-input` enable) is not valid
- [x] - tweak regexp in `useTimeParser` hook

chrome-capture

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any feature but make things better)

### CODE REVIEW

File: packages/ui/src/components/va-time-input/VaTimeInput.vue [hunk 1]
```diff
@@ -129,6 +129,12 @@ export default defineComponent({
       blur,
     })
 
+    watch(modelValueSync, () => {
+      if (!isValid.value && valueText.value === '') {
+        isValid.value = true
+      }
+    })
```
Comment (m0ksem) [inline packages/ui/src/components/va-time-input/VaTimeInput.vue:136]:
```suggestion
    watch(modelValueSync, () => {
      isValid.value = true
    })
```

This condition looks useless and makes modelValue required not to be null.

1. `if (isValid == false) isValid = true`
same as 
`isValid = true`

2. `valueText.value == ''` when `isValid is false` or `modelValue is null`
By default, modelValue is not required and validation of required rule controlled by VaInput, and it's text.


Double check if I correct.

**Review by m0ksem — CHANGES_REQUESTED** [review]

File: packages/ui/src/components/va-time-input/VaTimeInput.vue (hunk 1 above)
Comment (RVitaly1978) [reply packages/ui/src/components/va-time-input/VaTimeInput.vue]: fixed it

**Review by m0ksem — APPROVED** [review]
