### PR TITLE
fix: dismiss only last modal on esc

### LINKED ISSUE #1651: `Esc` closes all nested `VaModal`
**Vuestic-ui version:** 1.3.5

**Steps to reproduce**
1. go to https://vuestic.dev/en/ui-elements/modal#nested-modals
2. open first and second modals
3. press `esc`

**What is the expected behavior?**
should be closed only second (the last opened) modal

**What is the current behavior?**
both modals close
chrome-capture

**Other information**

### PR DESCRIPTION
**Pull request by LighthouseKeeperYN**
close #1651

Feedback appreciated. This works but I wish I could figure out how to fix this in less costyl fashion.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any feature but make things better)

### CODE REVIEW

File: packages/ui/src/components/va-modal/VaModal.vue [hunk 1]
```diff
@@ -213,7 +214,9 @@ export default defineComponent({
     const onAfterLeaveTransition = (el: HTMLElement) => emit('close', el)
 
     const listenKeyUp = (e: KeyboardEvent) => {
-      if (e.code === 'Escape' && !props.noEscDismiss && !props.noDismiss) {
+      const isLastNestedModal = !modal.value?.$el.nextElementSibling
```
Comment (RVitaly1978) [inline packages/ui/src/components/va-modal/VaModal.vue:217]: in the `body` after the last modal there can be one or more dropdowns (as well as user elements)

File: packages/ui/src/components/va-modal/VaModal.vue [hunk 2]
```diff
@@ -11,6 +11,7 @@
     <teleport :to="attachElement" :disabled="$props.disableAttachment">
       <modal-element
         name="va-modal"
+        ref="modal"
```
Comment (RVitaly1978) [inline packages/ui/src/components/va-modal/VaModal.vue:14]: Maybe
```suggestion
```
and below in 20th line: `<div class="va-modal" v-if="valueComputed" ref="modal">`

**Review by RVitaly1978 — CHANGES_REQUESTED** [review]

File: packages/ui/src/components/va-modal/VaModal.vue (hunk 1 above)
Comment (LighthouseKeeperYN) [reply packages/ui/src/components/va-modal/VaModal.vue:217]: I wonder If this could actually be a feature? So dropdown get dismissed on esc before the popup.

Comment (RVitaly1978) [reply packages/ui/src/components/va-modal/VaModal.vue:217]: Components like `VaToast` do not respond (are not removed from the `body`) when the `esc` key is pressed.

[the remark this answers is not in the document]
Comment (Derranion) [reply packages/ui/src/components/va-modal/VaModal.vue:217]: Here is complete solution:

```
    const listenKeyUp = (e: any) => {
      e.modalsCounter = e.modalsCounter ? e.modalsCounter + 1 : 1
      const modalNumber = e.modalsCounter

      const hideModal = () => {
        if (e.code === 'Escape' && !props.noEscDismiss && !props.noDismiss && e.modalsCounter === modalNumber) {
          cancel()
        }
      }

      setTimeout(hideModal, 30)
    }
```

**Review by Derranion — APPROVED** [review]
Glad that it helped :)

**Review by RVitaly1978 — APPROVED** [review]

**Review by rustem-nasyrov — APPROVED** [review]
