### PR TITLE
Fix#1278 Fix input docs

### LINKED ISSUE #1278: Missed translations in va-input docs api
chrome-capture

Required:
- [x] - add trsnslations
- [ ] - add example with attrs

### PR DESCRIPTION
**Pull request by RVitaly1978**
## Description
close #1278

changes:
- [x] add missed descriptions
- [x] add examples with `attrs` to docs and demo
- [x] remove redundant `expose` in **setup** fuction
- [x] update `va-form` validation

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Improvement/refactoring (non-breaking change that doesn't add any feature but make things better)

### CODE REVIEW

File: packages/ui/src/components/va-form/VaForm.vue [hunk 1]
```diff
@@ -79,9 +79,13 @@ export default defineComponent({
...
     const validate = () => { // NOTE: temporarily synchronous validation
-      const formValid = nestedFormElements.value
+      let formValid = true
+      nestedFormElements.value
         .filter(({ validate }) => validate)
-        .every((child) => child.validate())
+        .forEach((child) => {
+          const isValidChild = child.validate()
+          if (!isValidChild && formValid) { formValid = false }
+        })
```
[the remark this answers is not in the document]
Comment (RVitaly1978) [reply packages/ui/src/components/va-form/VaForm.vue:88]: In the case with `every`, validation in the form stops after the first `invalid` child.

**Review by LighthouseKeeperYN — APPROVED** [review]

File: packages/ui/src/components/va-form/VaForm.vue [hunk 2]
```diff
@@ -78,10 +78,12 @@ export default defineComponent({
       }
     }
 
+    // validation for every nested child
     const validate = () => { // NOTE: temporarily synchronous validation
       const formValid = nestedFormElements.value
         .filter(({ validate }) => validate)
-        .every((child) => child.validate())
+        .map((child) => child.validate()) // more readable than with 'forEach'
```
Comment (m0ksem) [inline packages/ui/src/components/va-form/VaForm.vue:85]: It's not forEach. It runs child.validate until any of result is false.

Comment (RVitaly1978) [reply packages/ui/src/components/va-form/VaForm.vue:85]: We want to validate each child element to show the user their validation status. So we use `map` and `every` method (for the human-readable reason we use these instead of `forEach`)
