### PR TITLE
Feat/sidebar fixes

### LINKED ISSUE #73: Documentation sandbox
Design: https://www.figma.com/file/RtRWUpAZkBxbD2rWp6k9CY/vuestic_documentation?node-id=7%3A2
image

## Features:
- [ ] Show code (template only)
- [ ] Github file link
- [ ] [Open in CodeSandbox](https://github.com/epicmaxco/vuestic-ui/issues/340)
- [ ] Copy code button

## Optional features 
(discuss with @asvae after main features are done, these are not highest priority, but would be nice to have):
- [ ] Should include JS if it's present
- [ ] Should include styles as a separate tab only if these are present.

## Notes
* Sandbox is English only. Translation is not needed. That also means that all description should be handled outside of sandbox.
* Please check refs source code as to not reinvent the wheel.

## Component examples from different frameworks

We don't need any of original framework features, but listing them just in case, as analysis was done.

Quasar
image

Vuetify - has theming included
image

Vue-ant design - has text embedded
image

Bootstrap-vue - allows code editing on page (not in sandbox)
image

iView - vertical split + embedded text + code half-hidden
image

### LINKED ISSUE #155: should not use !important style in va-sidebar to set content-wrap margin-left value
* **I'm submitting a ...**
  - [ ] bug report

> https://github.com/epicmaxco/vuestic-ui/blob/7314d580cdf4ae5930b0cb4662fd32eb2b382bee/src/components/vuestic-components/va-sidebar/VaSidebar.vue#L81

In my opinion, !important style is unreasonable in the above code. The user cannot override it when they need to. For example, I want to make the sidebar fully hidden on mobile device, so i override the minimized style. But the margin-left of content-wrap is unchangable and it is nonsense.

### LINKED ISSUE #207: Implement algolia search for docs
image

https://www.figma.com/file/RtRWUpAZkBxbD2rWp6k9CY/vuestic_documentation?node-id=7%3A2

* algolia [allows vue component usage](https://www.algolia.com/doc/guides/building-search-ui/getting-started/vue/), so we want to use our components.
* algolia [docsearch](https://docsearch.algolia.com/)

### LINKED ISSUE #251: Create docs page example
- [x] In navigation bar page should be in Contribution > DocumentationPageExample
- [x] There should be a description on what this page is for (documentation to work with documentation engine).
- [x] Page should have all current blocks.
- [x] Blocks should have descriptions where needed (which block serves which purpose).
- [x] Page should be excluded from navigation.
- [x] Page link should be added to contribution docs.
- [x] Page should explain, how `local` flag and versions operate.

### LINKED ISSUE #339: Sidebar component
# Docs

- [ ] Do after [docs boilerplate](#17) is done.

# Refs
* [Vuetify](https://vuetifyjs.com/en/components/navigation-drawers/)
* [Quasar](https://quasar.dev/layout/drawer)
* [Ant Design](https://www.antdv.com/components/drawer/)
* [iView](http://iview.talkingdata.com/#/components/drawer-en)

### LINKED ISSUE #414: flat button with vue-router
The flat button works incorrectly with vue-router. Hover state doesn't work with "to" prop.

### LINKED ISSUE #434: Language prefixed routes are broken
Links like this `/en/` on docs are broken. Should show home page instead.

### PR DESCRIPTION
**Pull request by SergeiPleshkov**
closes #339 
closes #155
closes #207
closes #73
closes #251
closes #414
closes #434 

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [X] Improvement/refactoring (non-breaking change that doesn't add any feature but make things better)

### CODE REVIEW

File: packages/docs/components/sidebar/Sidebar.vue [hunk 1]
```diff
@@ -31,29 +46,21 @@
...
+import { Component, Vue, Prop } from 'vue-property-decorator'
+import { NavigationRoute } from './NavigationRoutes'
+
+@Component({})
 export default class Sidebar extends Vue {
-  data () {
+  @Prop({ type: Boolean, required: true }) readonly minimized!: boolean
+  @Prop({ type: Array, default: [] }) readonly items!: NavigationRoute[]
+
+  get categoryTitleStyle () {
```
Comment (asvae) [inline packages/docs/components/sidebar/Sidebar.vue:57]: css?

File: packages/ui/src/components/vuestic-components/va-sidebar/VaSidebarLinkGroup.vue [hunk 2]
```diff
@@ -70,115 +71,139 @@
       </a>
       <div
         class="va-sidebar-link-group__submenu in"
-        :style="{backgroundColor: $themes[color]}"
+        :style="{backgroundColor: getColor(color)}"
```
Comment (asvae) [inline packages/ui/src/components/vuestic-components/va-sidebar/VaSidebarLinkGroup.vue:74]: this won't work.

File: packages/docs/components/sidebar/NavigationRoutes.ts [hunk 3]
```diff
@@ -3,6 +3,8 @@ import scheme from './navigationScheme.json'
```
Comment (asvae) [inline packages/docs/components/sidebar/NavigationRoutes.ts:3]: Padding

image

File: packages/docs/components/sidebar/NavigationRoutes.ts [hunk 4]
```diff
@@ -3,6 +3,8 @@ import scheme from './navigationScheme.json'
 
 export type NavigationRoute = {
   name: string,
+  childrenCategories?: TranslationString[],
```
Comment (asvae) [inline packages/docs/components/sidebar/NavigationRoutes.ts:6]: Doesn't seem to be used for anything.

File: packages/docs/components/sidebar/Sidebar.vue [hunk 5]
```diff
@@ -1,64 +1,130 @@
...
-          :active-by-default="item.name === route.name"
-          :to="item.name"
-        >
-          <span slot="title">{{ $t(item.displayName) }}</span>
-        </va-sidebar-link>
-      </template>
+      <va-list class="sidebar__links">
+        <va-expand-group v-model="value">
+          <va-expand
+            v-for="(item, key) in items"
```
Comment (asvae) [inline packages/docs/components/sidebar/Sidebar.vue:10]: What is items?

File: packages/docs/components/sidebar/Sidebar.vue [hunk 6]
```diff
@@ -1,64 +1,130 @@
...
+              <va-list-item class="sidebar__category">
+                <va-list-item-section class="sidebar__category__section">
+                  <va-list-item-label class="sidebar__category__label">
+                    {{ $t(item.displayName) }}
+                  </va-list-item-label>
+                </va-list-item-section>
+                <va-list-item-section icon>
+                  <va-icon
+                    :name="value[key] ? 'expand_less' : 'expand_more'"
+                    :color="value[key] ? '#2c82e0' : ''"
```
Comment (asvae) [inline packages/docs/components/sidebar/Sidebar.vue:25]: Can't we move this color somwhere?
Also check other places. I see this color being used elsewhere.

File: packages/docs/components/sidebar/Sidebar.vue [hunk 7]
```diff
@@ -1,64 +1,130 @@
...
+import { NavigationRoute } from './NavigationRoutes'
+
+@Component({})
 export default class Sidebar extends Vue {
-  data () {
-    return {
-      items: navigationRoutes.routes,
+  value = []
+
+  @Prop({ type: Array, default: [] }) readonly items!: NavigationRoute[]
```
Comment (asvae) [inline packages/docs/components/sidebar/Sidebar.vue:70]: default: () => []

Your way won't work.

Also, any reason to have default here?

File: packages/docs/components/sidebar/Sidebar.vue [hunk 8]
```diff
@@ -1,64 +1,130 @@
...
+}
+</script>
+
+<style lang="scss" scoped>
+.sidebar {
+  padding-top: 2.5625rem;
+  // padding-bottom: 1rem;
```
Comment (asvae) [inline packages/docs/components/sidebar/Sidebar.vue:77]: remove comments?

File: packages/docs/components/sidebar/Sidebar.vue [hunk 9]
```diff
@@ -1,64 +1,130 @@
...
+    // max-height: calc(100vh - 1rem);
+    padding-bottom: 1rem;
+  }
+
+  &__link {
+    padding: 1rem 0 1rem 2rem;
+    line-height: 1.1;
+
+    &:hover {
+      background: #ecf4f8;
```
Comment (asvae) [inline packages/docs/components/sidebar/Sidebar.vue:90]: color to variable?

File: packages/docs/components/sidebar/SidebarOld.vue [hunk 10]
```diff
@@ -0,0 +1,77 @@
+<template>
```
Comment (asvae) [inline packages/docs/components/sidebar/SidebarOld.vue:1]: Maybe remove this component?
What's its purpose?

File: packages/docs/pages/index.vue [hunk 11]
```diff
@@ -5,7 +5,7 @@
       class="base-layout__header"
     />
     <div class="base-layout__main">
-      <Sidebar v-if="isSidebarVisible" :minimized="!isSidebarVisible" />
+      <Sidebar v-if="isSidebarVisible" :minimized="!isSidebarVisible" :items="navigationItems" />
```
Comment (asvae) [inline packages/docs/pages/index.vue:8]: What's the reason to keep v-if here?
I see the comment below, but it doesn't tell much.

File: packages/docs/pages/index.vue [hunk 12]
```diff
@@ -73,6 +74,10 @@ export default class Index extends Vue {
     }
   }
 
+  get navigationItems () {
```
Comment (asvae) [inline packages/docs/pages/index.vue:77]: Please use consistent naming. `Routes` should not suddenly become `NavigationItems`.

File: packages/ui/src/components/vuestic-components/va-expand/VaExpand.demo.vue [hunk 13]
```diff
@@ -6,7 +6,7 @@
         style="width: 400px;"
         :header="expandHeader"
       >
-        <div>
+        <div style="padding: 1rem;">
```
Comment (asvae) [inline packages/ui/src/components/vuestic-components/va-expand/VaExpand.demo.vue:9]: You can move these to scoped styles just to keep demo a bit cleaner.
(I know I said "inline styles are best" before, but that opinion changed :) )

File: packages/ui/src/components/vuestic-components/va-list/VaListItem.vue [hunk 14]
```diff
@@ -63,7 +63,7 @@ export default class VaListItem extends Mixins(
 
 .va-list-item {
   display: flex;
-  padding: $list-item-padding;
+  padding: 0.5rem;
```
Comment (asvae) [inline packages/ui/src/components/vuestic-components/va-list/VaListItem.vue:66]: Can't we keep variables for at least some list css items?

File: packages/ui/src/components/vuestic-components/va-sidebar/VaSidebar.demo.vue [hunk 15]
```diff
@@ -27,38 +61,186 @@
...
+      </div>
     </VbCard>
   </VbDemo>
 </template>
 
 <script>
 import VaSidebar from '../../vuestic-components/va-sidebar/VaSidebar'
-import SidebarLinkGroup from './VaSidebarLinkGroup'
-import SidebarLink from './VaSidebarLink'
+import VaRadio from '../va-radio/VaRadio'
```
Comment (asvae) [inline packages/ui/src/components/vuestic-components/va-sidebar/VaSidebar.demo.vue:216]: I see no point having all of these in demo.

File: packages/ui/src/components/vuestic-components/va-sidebar/VaSidebar.demo.vue [hunk 16]
```diff
@@ -27,38 +61,186 @@
...
+    VaExpandGroup,
+    VaList,
+    VaListItem,
+    VaListItemSection,
+    VaListLabel,
+    VaListItemLabel,
   },
   data () {
     return {
+      options: [
```
Comment (asvae) [inline packages/ui/src/components/vuestic-components/va-sidebar/VaSidebar.demo.vue:248]: Most of the data is also not needed.

File: packages/docs/pages/index.vue (hunk 11 above)
Comment (SergeiPleshkov) [reply packages/docs/pages/index.vue:8]: We should rework it when we will implement iconset handling and will show icons when sidebar is hidden.

File: packages/ui/src/components/vuestic-components/va-expand/VaExpand.demo.vue (hunk 13 above)
Comment (SergeiPleshkov) [reply packages/ui/src/components/vuestic-components/va-expand/VaExpand.demo.vue:9]: Should i remove it from everywhere or just this demo?

Comment (asvae) [reply packages/ui/src/components/vuestic-components/va-expand/VaExpand.demo.vue:9]: @asvae up to you. It's not a big deal.

File: packages/docs/components/DocsNavigation.vue [hunk 17]
```diff
@@ -0,0 +1,102 @@
...
+      }, 1500)
+    },
+  },
+}
+</script>
+
+<style lang="scss">
+@import "../ui/src/components/vuestic-sass/resources/resources";
+
+.docs-nav {
```
Comment (asvae) [inline packages/docs/components/DocsNavigation.vue:76]: Use full name.

File: packages/docs/components/page-configs/contribution/documentation-page/api-options.ts [hunk 18]
```diff
@@ -0,0 +1,33 @@
+import { ManualApiOptions } from 'vuestic-ui/src/services/api-docs/ManualApiOptions'
```
Comment (asvae) [inline packages/docs/components/page-configs/contribution/documentation-page/api-options.ts:1]: We probably want to have that page in sidebar as well.

File: packages/docs/components/page-configs/contribution/documentation-page/page-config.ts [hunk 19]
```diff
@@ -0,0 +1,140 @@
...
+    translationString: 'documentationPage.blocktypes.subtitle.title',
+  },
+  {
+    type: BlockType.PARAGRAPH,
+    translationString: 'documentationPage.blocktypes.subtitle.text',
+  },
+  {
+    type: BlockType.CODE,
+    code: blocktypes.subtitle,
+  },
```
Comment (asvae) [inline packages/docs/components/page-configs/contribution/documentation-page/page-config.ts:46]: did you try to add blocktypes.subtitle directly below the example? I.e. you'll be able to see what it compiles to.

File: packages/docs/components/page-configs/va-sidebar/api-options.ts [hunk 20]
```diff
@@ -0,0 +1,24 @@
+import { ManualApiOptions } from 'vuestic-ui/src/services/api-docs/ManualApiOptions'
+
+export default {
+  props: {
+    minimized: {
```
Comment (asvae) [inline packages/docs/components/page-configs/va-sidebar/api-options.ts:5]: should have stateful

File: packages/docs/components/sidebar/Sidebar.vue [hunk 21]
```diff
@@ -1,64 +1,133 @@
...
+          <div v-for="(childRoute, index) in route.children" :key="index">
+            <va-list-label
+              v-if="childRoute.category"
+              class="sidebar__subcategory__label"
+              color="gray"
+            >
+              {{ $t(childRoute.category) }}
+            </va-list-label>
+            <va-list-item
+              :to="childRoute.name"
```
Comment (asvae) [inline packages/docs/components/sidebar/Sidebar.vue:36]: This doesn't work when you go to "Contribution",  then click on any page on sidebar.

File: packages/docs/components/sidebar/Sidebar.vue [hunk 22]
```diff
@@ -1,64 +1,133 @@
...
-      required: true,
-    },
-  },
+  components: { VaSearch },
 })
 export default class Sidebar extends Vue {
-  data () {
-    return {
-      items: navigationRoutes.routes,
+  value = [] as Array<boolean|undefined>
```
Comment (asvae) [inline packages/docs/components/sidebar/Sidebar.vue:62]: why not `boolean[]`?

File: packages/docs/components/sidebar/Sidebar.vue [hunk 23]
```diff
@@ -1,64 +1,133 @@
...
+
+  @Prop({ type: Array }) readonly navigationRoutes!: NavigationRoute[]
```
Comment (asvae) [inline packages/docs/components/sidebar/Sidebar.vue:64]: Most likely you want to either mark it as required or define default. Right now sidebar will break if no navigation routes are provided.

File: packages/docs/components/sidebar/Sidebar.vue [hunk 24]
```diff
@@ -1,64 +1,133 @@
...
+  @Prop({ type: Boolean, default: false }) readonly minimized!: boolean
+
+  mounted () {
+    this.value = this.navigationRoutes.map((route, index) => this.value[index] || route?.children?.some(({ name }) => this.$router.currentRoute.name?.includes(name)))
```
Comment (asvae) [inline packages/docs/components/sidebar/Sidebar.vue:68]: Split into several lines.

File: packages/docs/components/sidebar/Sidebar.vue [hunk 25]
```diff
@@ -1,64 +1,133 @@
...
+
+  &__subcategory {
+    &__label {
+      &:not(:first-child) {
+        padding-top: 1rem;
+      }
+
+      text-align: left;
+      padding-left: 1.5rem;
+      color: #8396a5;
```
Comment (asvae) [inline packages/docs/components/sidebar/Sidebar.vue:129]: Move this color to variable. It's used in a couple of other places.

File: packages/docs/components/sidebar/va-sidebar/VaSearch.vue [hunk 26]
```diff
@@ -0,0 +1,191 @@
...
+  </form>
+</template>
+
+<script lang="ts">
+import { Component, Vue } from 'vue-property-decorator'
+
+@Component({
+  name: 'VaSearch',
+})
+export default class VaSearch extends Vue {
```
Comment (asvae) [inline packages/docs/components/sidebar/va-sidebar/VaSearch.vue:26]: Maybe AlgoliaSearch?

File: packages/docs/examples/va-sidebar/Color.vue [hunk 27]
```diff
@@ -0,0 +1,16 @@
+<template>
```
Comment (asvae) [inline packages/docs/examples/va-sidebar/Color.vue:1]: Should use VaList component and a bit of variety. We want examples to look similarly to standard components.

File: packages/docs/locales/en/en.json [hunk 28]
```diff
@@ -639,20 +649,34 @@
...
       "events": {
-        "click" :"Emitted when user clicked on backtop"
+        "click": "Emitted when user clicked on backtop"
       },
       "methods": {},
       "slots": {
         "default": "Slot for backtop content"
       }
+    },
+    "VaAppBar": {
```
Comment (asvae) [inline packages/docs/locales/en/en.json:659]: Do you have a follow up on this?

File: packages/docs/locales/en/en.json [hunk 29]
```diff
@@ -702,6 +727,50 @@
...
   },
+  "documentationPage": {
+    "title": "Documentation Page",
+    "description": "It's documentation to work with a documentation engine. Try to use script `generate:component` to generate required files: [api-options](https://github.com/epicmaxco/vuestic-ui/blob/develop/packages/docs/components/page-configs/va-button/api-options.ts) and [page-config](https://github.com/epicmaxco/vuestic-ui/blob/develop/packages/docs/components/page-configs/va-button/page-config.ts). It will allow you to skip unnecessary steps and simplify you to create docs.",
+    "pageConfigTitle": "Page Config",
+    "pageConfigText": "Page config allows you to build an documentation page. Commonly documentation page is an array of blocks.",
+    "blocktypes": {
+      "title": {
+        "title": "Title",
+        "text": "This block used once per page to describe what the page is about."
```
Comment (asvae) [inline packages/docs/locales/en/en.json:738]: "Page title. Mandatory."

File: packages/docs/components/page-configs/va-sidebar/api-options.ts (hunk 20 above)
Comment (SergeiPleshkov) [reply packages/docs/components/page-configs/va-sidebar/api-options.ts:5]: it has, but not the local one

File: packages/docs/locales/en/en.json (hunk 28 above)
Comment (SergeiPleshkov) [reply packages/docs/locales/en/en.json:659]: Dima is working on it.

Comment (asvae) [reply packages/docs/locales/en/en.json:659]: @SergeiPleshkov so are you both working on same PR currently? o.o

File: packages/docs/components/sidebar/navigationScheme.ts [hunk 30]
```diff
@@ -0,0 +1,167 @@
+import { NavigationScheme } from './NavigationRoutes'
+
+export const navigationScheme: NavigationScheme = {
+  root: {
```
Comment (asvae) [inline packages/docs/components/sidebar/navigationScheme.ts:4]: Is this being used for something?

File: packages/docs/locales/en/en.json (hunk 28 above)
Comment (Kushich) [reply packages/docs/locales/en/en.json:659]: @asvae No, it's in a separate PR

**Review by asvae — CHANGES_REQUESTED** [review]
Fair amount of things still need fixing.
Feel free to move to separate issue if you think something takes too much effort.

File: packages/docs/components/DocsNavigation.vue [hunk 31]
```diff
@@ -0,0 +1,102 @@
+<template>
+  <div class="docs-navigation">
+    <va-button
+      flat
+      size="small"
+      class="docs-nav__button"
```
Comment (asvae) [inline packages/docs/components/DocsNavigation.vue:6]: I'm pretty sure these `docs-nav` classes are doing nothing.

File: packages/docs/components/DocsNavigation.vue [hunk 32]
```diff
@@ -0,0 +1,102 @@
+<template>
```
[the remark this answers is not in the document]
Comment (SergeiPleshkov) [reply packages/docs/components/DocsNavigation.vue:1]: It was used to show usability of minimized width prop.

File: packages/docs/components/sidebar/Sidebar.vue [hunk 33]
```diff
@@ -1,64 +1,175 @@
...
+            <va-list-label
+              v-if="childRoute.category"
+              class="sidebar__subcategory__label"
+              color="gray"
+            >
+              {{ $t(childRoute.category) }}
+            </va-list-label>
+            <va-list-item
+              :to="
+                `/${$root.$i18n.locale}/${childRoute.name}${childRoute.hash ||
```
[the remark this answers is not in the document]
Comment (SergeiPleshkov) [reply packages/docs/components/sidebar/Sidebar.vue:37]: so i just have to make one link  "documentation page" in sidebar?

File: packages/docs/components/sidebar/Sidebar.vue [hunk 34]
```diff
@@ -1,64 +1,175 @@
...
+  value = [] as boolean[]
+
+  @Prop({ type: Array, default: () => [] })
+  readonly navigationRoutes!: NavigationRoute[]
+
+  @Prop({ type: Boolean, default: false }) readonly minimized!: boolean
+
+  mounted () {
+    this.setActiveExpand()
+    if (this.$route.hash) {
```
[the remark this answers is not in the document]
Comment (SergeiPleshkov) [reply packages/docs/components/sidebar/Sidebar.vue:74]: it doesn't work fine with programmatic navigation

File: packages/ui/src/components/vuestic-components/va-expand/VaExpand.vue [hunk 35]
```diff
@@ -170,11 +147,35 @@ export default class VaExpand extends Mixins(
   }
 
   getHeight () {
-    const node = this.$slots.default?.[0].elm as HTMLElement
-    return node ? `calc(${node.clientHeight}px + 2rem)` : '100%'
+    const node = [...((this.$refs.body as any)?.childNodes || [])]
+    return node.reduce((result: number, node: HTMLElement) => {
+      // handling text nodes height
+      result += node.nodeType === 3 ? this.getTextNodeHeight(node) : node.clientHeight
```
[the remark this answers is not in the document]
Comment (SergeiPleshkov) [reply packages/ui/src/components/vuestic-components/va-expand/VaExpand.vue:153]: textNode. we can't get it's height normal way. will make a constant.

File: packages/ui/src/components/vuestic-components/va-expand/VaExpand.vue [hunk 36]
```diff
@@ -170,11 +147,35 @@ export default class VaExpand extends Mixins(
...
+      return result
+    }, 0) + 'px'
   }
 
-  mount () {
+  getTextNodeHeight (textNode: Node) {
+    let height = 0
+    if (document.createRange) {
```
[the remark this answers is not in the document]
Comment (SergeiPleshkov) [reply packages/ui/src/components/vuestic-components/va-expand/VaExpand.vue:160]: we need to calculate height of text node if it's not in a block, and we can't get it by offsetHeight or smth else

File: packages/docs/components/DocsSubtitle.vue [hunk 37]
```diff
@@ -17,7 +17,8 @@ import MarkdownView from '../utilities/markdown-view/MarkdownView.vue'
 export default class DocsSubtitle extends Mixins(ColorThemeMixin) {
   @Prop({ type: String }) text!: TranslationString
   get anchor () {
-    return kebabCase(this.$t(this.text) as string)
+    // @ts-ignore
```
Comment (asvae) [inline packages/docs/components/DocsSubtitle.vue:20]: Why ts-ignore here?

File: packages/docs/components/sidebar/NavigationRoute.ts [hunk 38]
```diff
@@ -1,19 +1,14 @@
 import { TranslationString } from '../../../ui/src/services/api-docs/ManualApiOptions'
-import scheme from './navigationScheme.json'
 
 export type NavigationRoute = {
   name: string,
+  path?: string,
```
Comment (asvae) [inline packages/docs/components/sidebar/NavigationRoute.ts:5]: path doesn't seem to be used anywhere

File: packages/docs/components/sidebar/NavigationRoute.ts [hunk 39]
```diff
@@ -1,19 +1,14 @@
...
+  childrenCategories?: TranslationString[],
```
Comment (asvae) [inline packages/docs/components/sidebar/NavigationRoute.ts:6]: Doesn't seem seem to be used.

File: packages/docs/components/sidebar/Sidebar.vue [hunk 40]
```diff
@@ -1,64 +1,162 @@
 <template>
-  <va-sidebar :minimized="minimized">
-    <template slot="menu">
-      <template v-for="(item, key) in items">
-        <va-sidebar-link-group
-          v-if="item.children"
+  <va-sidebar class="sidebar" color="secondary" v-model="minimized">
```
Comment (asvae) [inline packages/docs/components/sidebar/Sidebar.vue:2]: Sidebar links are not loaded in nuxt.
image

Comment (asvae) [inline packages/docs/components/sidebar/Sidebar.vue:2]: Navigation is not reactive:
image

File: packages/docs/components/sidebar/Sidebar.vue [hunk 41]
```diff
@@ -1,64 +1,175 @@
...
+    if (!value) {
+      return
     }
+    location.href = value
+    this.setActiveExpand()
   }
 
-  get route () {
-    return this.$route || {}
+  setActiveExpand () {
```
[the remark this answers is not in the document]
Comment (asvae) [reply packages/docs/components/sidebar/Sidebar.vue:73]: And it isn't. @SergeiPleshkov
Why this was marked as resolved?

**Review by asvae — CHANGES_REQUESTED** [review]

File: packages/ui/src/services/api-docs/ApiDocs.vue [hunk 42]
```diff
@@ -167,6 +171,10 @@ export default class ApiDocs extends Vue {
     font-family: "Source Code Pro";
     font-size: 16px;
 
+    &__row {
+      border-bottom: 1px solid #f4f8fa;
```
[the remark this answers is not in the document]
Comment (asvae) [reply packages/ui/src/services/api-docs/ApiDocs.vue]: Not fixed. Why this is marked as resolved?
image

File: packages/ui/src/components/vuestic-components/va-expand/VaExpand.vue [hunk 43]
```diff
@@ -187,24 +188,16 @@ export default class VaExpand extends Mixins(
...
-  margin: 0.5rem;
-
-  & + & {
-    margin-top: 1.5rem;
-  }
 
   &__body {
-    height: 0;
-    transition: ease-in 0.3s;
+    transition: height linear 0.3s;
```
[the remark this answers is not in the document]
Comment (asvae) [reply packages/ui/src/components/vuestic-components/va-expand/VaExpand.vue:202]: Did you check how it works?
Small expand is instant.
And big is linear.

Previous solution was better.

File: packages/ui/src/components/vuestic-components/va-expand/VaExpand.vue [hunk 44]
```diff
@@ -187,24 +188,16 @@ export default class VaExpand extends Mixins(
 }
 </script>
 
-<style lang="scss">
+<style lang="scss" scoped>
```
[the remark this answers is not in the document]
Comment (asvae) [reply packages/ui/src/components/vuestic-components/va-expand/VaExpand.vue:195]: What's this?
image

File: packages/ui/src/components/vuestic-components/va-expand/VaExpand.vue [hunk 45]
```diff
@@ -170,11 +147,35 @@ export default class VaExpand extends Mixins(
...
+        const rect = range.getBoundingClientRect()
+        if (rect) {
+          height = rect.bottom - rect.top
+        }
+      }
+    }
+    return height
+  }
+
+  @Watch('childValue')
```
[the remark this answers is not in the document]
Comment (asvae) [reply packages/ui/src/components/vuestic-components/va-expand/VaExpand.vue]: Not fixed.

File: packages/ui/src/components/vuestic-components/va-expand/VaExpand.vue [hunk 46]
```diff
@@ -170,11 +147,35 @@ export default class VaExpand extends Mixins(
...
+    }, 0) + 'px'
   }
 
-  mount () {
+  getTextNodeHeight (textNode: Node) {
+    let height = 0
+    if (document.createRange) {
+      const range = document.createRange()
+      range.selectNodeContents(textNode)
+      if (range.getBoundingClientRect) {
```
[the remark this answers is not in the document]
Comment (asvae) [reply packages/ui/src/components/vuestic-components/va-expand/VaExpand.vue]: `let height = 0` is not needed here.

File: packages/docs/components/sidebar/Sidebar.vue (hunk 34 above)
[the remark this answers is not in the document]
Comment (asvae) [reply packages/docs/components/sidebar/Sidebar.vue]: Can you show me what exactly doesn't work?

File: packages/ui/src/components/vuestic-components/va-expand/VaExpand.vue (hunk 36 above)
[the remark this answers is not in the document]
Comment (asvae) [reply packages/ui/src/components/vuestic-components/va-expand/VaExpand.vue]: `let height = 0` is not needed here.

File: packages/ui/src/components/vuestic-components/va-expand-group/VaExpandGroup.vue [hunk 47]
```diff
@@ -25,10 +25,10 @@ export default class VaExpandGroup extends Mixins(
   ExpandGroupPropsMixin,
 ) {
   @Provide() accordion = {
-    onChildChange: (child: any, state: any) => this.onChildChange(child, state),
+    onChildChange: this.onChildChange,
```
[the remark this answers is not in the document]
Comment (asvae) [reply packages/ui/src/components/vuestic-components/va-expand-group/VaExpandGroup.vue]: `state` is unused.
image

File: packages/docs/components/sidebar/Sidebar.vue [hunk 48]
```diff
@@ -1,64 +1,164 @@
...
+          <div v-for="(childRoute, index) in route.children" :key="index">
+            <va-list-label
+              v-if="childRoute.category"
+              class="sidebar__subcategory__label"
+              color="gray"
+            >
+              {{ $t(childRoute.category) }}
+            </va-list-label>
+            <va-list-item
+              tag="nuxt-link"
```
Comment (asvae) [inline packages/docs/components/sidebar/Sidebar.vue:36]: Would you imagine user to use the same contraption to get proper links in their templates?

Interface should be as simple as `<va-list-item :to="path"/>` and then component can decide default behavior based on environment (whether is has nuxt or not, whether it has router connected or not).

Feel free to move that to separate issue. So that we can close this one.

File: packages/ui/src/components/vuestic-components/va-expand/VaExpand.vue [hunk 49]
```diff
@@ -255,24 +252,23 @@ export default class VaExpand extends Mixins(
...
     }
 
-    &--active {
-      .va-expand {
-        &__header {
-          &__content {
-            border-radius: 0.375rem 0.375rem 0 0;
-            transition: ease-in 0.3s;
-          }
+    & .va-expand--active {
```
Comment (asvae) [inline packages/ui/src/components/vuestic-components/va-expand/VaExpand.vue:255]: This does nothing.
