### PR TITLE
fix: files list items disabled state

### LINKED ISSUE #2153: Va-file-upload allows file removal with the disable attribute.
**Vuestic-ui version:** 1.4.7

**Steps to reproduce**
  <template>
  <va-file-upload v-model="basic" />
</template>

Upload a file.
Set the disabled attribute programatically.
Remove the file with the red x

**What is the expected behavior?**
You should not be able to remove a file in a disabled UI element.

**What is the current behavior?**
You can remove the file in the otherwise disabled upload component.

**Other information**

### PR DESCRIPTION
**Pull request by rustem-nasyrov**
Close #2153

## Description
- Added disabled states for the removing button in the files list items.
- Added `useStrictInject` composable.
## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] Improvement/refactoring (non-breaking change that doesn't add any feature but make things better)

### CODE REVIEW

File: packages/ui/src/components/va-file-upload/VaFileUploadUndo/VaFileUploadUndo.vue [hunk 1]
```diff
@@ -58,7 +58,7 @@ export default defineComponent({
       vertical: props.vertical,
     }))
 
-    const undoDurationStyle = computed(() => `${undoDuration.value}ms`)
+    const undoDurationStyle = computed(() => `${undoDuration?.value}ms`)
```
Comment (aluarius) [inline packages/ui/src/components/va-file-upload/VaFileUploadUndo/VaFileUploadUndo.vue:61]: Is `undefined` converts to `0` in styles block or throws warning? If you not sure about this, let's make: `${undoDuration?.value ?? 0}ms`

**Review by aluarius — APPROVED** [review]

File: packages/ui/src/components/va-file-upload/VaFileUploadUndo/VaFileUploadUndo.vue (hunk 1 above)
Comment (rustem-nasyrov) [reply packages/ui/src/components/va-file-upload/VaFileUploadUndo/VaFileUploadUndo.vue:61]: Doesn't it will replace with default `inject` value from above?

File: packages/ui/src/components/va-file-upload/VaFileUploadGalleryItem/VaFileUploadGalleryItem.vue [hunk 2]
```diff
@@ -43,12 +44,13 @@
...
 
 <script lang="ts">
-import { defineComponent, onMounted, ref, watch, computed, PropType } from 'vue'
+import { defineComponent, inject, onMounted, ref, watch, computed, PropType } from 'vue'
 
 import { colorToRgba } from '../../../services/color-config/color-functions'
 import { useFocus, useBem } from '../../../composables'
 
 import type { ConvertedFile } from '../types'
+import { VaFileUploadKey } from '../types'
```
Comment (RVitaly1978) [inline packages/ui/src/components/va-file-upload/VaFileUploadGalleryItem/VaFileUploadGalleryItem.vue:53]:
```suggestion
import type { ConvertedFile, VaFileUploadKey } from '../types'
```

File: packages/ui/src/components/va-file-upload/VaFileUploadListItem/VaFileUploadListItem.vue [hunk 3]
```diff
@@ -14,39 +14,40 @@
...
-          aria-hidden="false"
-          aria-label="remove file"
-          tabindex="0"
+        <va-button
+          :disabled="disabled"
+          flat
           color="danger"
+          icon="clear"
+          class="va-file-upload-list-item__delete"
+          aria-label="remove image"
```
Comment (RVitaly1978) [inline packages/ui/src/components/va-file-upload/VaFileUploadListItem/VaFileUploadListItem.vue:23]: image?

**Review by RVitaly1978 — APPROVED** [review]

File: packages/ui/src/components/va-file-upload/VaFileUploadUndo/VaFileUploadUndo.vue (hunk 1 above)
Comment (aluarius) [reply packages/ui/src/components/va-file-upload/VaFileUploadUndo/VaFileUploadUndo.vue:61]: Yes, it will, but `undefined` can also be provided-injected, overwriting default value. For some reasons you changed to `?.`, so there are some ways for `undoDuration.value` to be `undefined`.

**Comment by rustem-nasyrov** [comment]
@asvae can you review please?

File: packages/ui/src/components/va-file-upload/VaFileUploadListItem/VaFileUploadListItem.vue [hunk 4]
```diff
@@ -135,6 +151,8 @@ export default defineComponent({
     font-size: 1.5rem;
     cursor: pointer;
 
+    --va-button-size: 1.5rem;
+
     &:focus {
       @include focus-outline;
     }
```
Comment (RVitaly1978) [inline packages/ui/src/components/va-file-upload/VaFileUploadListItem/VaFileUploadListItem.vue:158]: Doesn't `VaButton` have a `focus` state by default?

File: packages/ui/src/components/va-file-upload/VaFileUploadSingleItem/VaFileUploadSingleItem.vue [hunk 5]
```diff
@@ -16,21 +19,30 @@
...
   },
+
   emits: ['remove'],
+
   props: {
     file: { type: Object as PropType<ConvertedFile | null>, default: null },
   },
+
+  setup: () => ({
+    disabled: useStrictInject<VaFileUploadInject>(VaFileUploadKey, INJECTION_ERROR_MESSAGE).disabled || false,
```
Comment (RVitaly1978) [inline packages/ui/src/components/va-file-upload/VaFileUploadSingleItem/VaFileUploadSingleItem.vue:44]: in `VaFileUpload` we have this prop with default value:
`disabled: { type: Boolean, default: false },`
Why do we need a fallback value here?

File: packages/ui/src/components/va-file-upload/VaFileUploadUndo/VaFileUploadUndo.vue [hunk 6]
```diff
@@ -46,19 +49,15 @@ export default defineComponent({
...
-    })
+      deletedFileMessage,
+    } = useStrictInject<VaFileUploadInject>(VaFileUploadKey, INJECTION_ERROR_MESSAGE)
 
     const computedClasses = useBem('va-file-upload-undo', () => ({
       vertical: props.vertical,
     }))
 
-    const undoDurationStyle = computed(() => `${undoDuration.value}ms`)
+    const undoDurationStyle = computed(() => `${undoDuration?.value || 3000}ms`)
```
Comment (RVitaly1978) [inline packages/ui/src/components/va-file-upload/VaFileUploadUndo/VaFileUploadUndo.vue:60]:
```suggestion
    const undoDurationStyle = computed(() => `${undoDuration.value ?? 0}ms`)
```
If the user doesn't want the duration and sets it to 0, we should use the `v-if` directive with `va-progress-bar` in the template

File: packages/ui/src/components/va-file-upload/types.ts [hunk 7]
```diff
@@ -1,12 +1,14 @@
...
-export type VaFileUpload = {
-  undoDuration: Ref<number>
-  undoButtonText: Ref<string>
-  deletedFileMessage: Ref<string>
+export type VaFileUploadInject = {
+  undo?: Ref<boolean>
+  disabled?: Ref<boolean>
+  undoDuration?: Ref<number>
+  undoButtonText?: Ref<string>
+  deletedFileMessage?: Ref<string>
```
Comment (RVitaly1978) [inline packages/ui/src/components/va-file-upload/types.ts:8]:
```suggestion
  undo: Ref<boolean>
  disabled: Ref<boolean>
  undoDuration: Ref<number>
  undoButtonText: Ref<string>
  deletedFileMessage: Ref<string>
```

**Review by RVitaly1978 — CHANGES_REQUESTED** [review]

**Comment by RVitaly1978** [comment]
We also need to remove the arguments that are set for the components in the template if they receive these props from injection.
Like this:
```ts
      <va-file-upload-gallery-item
        v-for="(file, index) in filesList"
        role="listitem"
        :file="file"
        :key="file.name"
        :color="color"
        :undo="undo"
        :undoDuration="undoDuration"
        @remove="$emit('remove', index)"
      />
```

File: packages/ui/src/components/va-file-upload/VaFileUploadUndo/VaFileUploadUndo.vue (hunk 6 above)
Comment (rustem-nasyrov) [reply packages/ui/src/components/va-file-upload/VaFileUploadUndo/VaFileUploadUndo.vue:60]: I think here will fit the `undefined` or `null` values for the undo-duration prop, I'll note it in the property description in the docs page.

File: packages/ui/src/components/va-file-upload/VaFileUploadGalleryItem/VaFileUploadGalleryItem.vue [hunk 8]
```diff
@@ -46,29 +48,38 @@
...
-    undo: { type: Boolean, default: false },
-    undoDuration: { type: Number, default: 3000 },
   },
+
   setup (props, { emit }) {
+    const {
+      undo,
+      disabled,
+      undoDuration,
+    } = useStrictInject<VaFileUploadInject>(VaFileUploadKey, INJECTION_ERROR_MESSAGE)
```
Comment (asvae) [inline packages/ui/src/components/va-file-upload/VaFileUploadGalleryItem/VaFileUploadGalleryItem.vue:82]: `<VaFileUploadInject>` actually does nothing. You have return type defined in `VaFileUploadKey`, which TypeScript can use.

File: packages/ui/src/components/va-file-upload/VaFileUpload.vue [hunk 9]
```diff
@@ -197,21 +201,18 @@ export default defineComponent({
       }
     })
 
-    provide(VaFileUploadKey, {
-      undoDuration: toRef(props, 'undoDuration'),
-      undoButtonText: toRef(props, 'undoButtonText'),
-      deletedFileMessage: toRef(props, 'deletedFileMessage'),
-    })
+    provide(VaFileUploadKey, toRefs(props))
```
Comment (asvae) [inline packages/ui/src/components/va-file-upload/VaFileUpload.vue:204]: Might be better idea to only pass stuff you want other components to use.

File: packages/ui/src/components/va-file-upload/VaFileUpload.vue [hunk 10]
```diff
@@ -1,7 +1,7 @@
 <template>
```
Comment (asvae) [inline packages/ui/src/components/va-file-upload/VaFileUpload.vue:1]: Would be great to see some demos on disabled behavior.

Comment (asvae) [inline packages/ui/src/components/va-file-upload/VaFileUpload.vue:1]: Do we even need red crosses/bins for disabled items? I think they only add to confusion and we can remove them safely?

**Review by asvae — APPROVED** [review]
Yep, looks good :)

**Review by m0ksem — APPROVED** [review]

File: packages/ui/src/components/va-file-upload/VaFileUploadSingleItem/VaFileUploadSingleItem.vue [hunk 11]
```diff
@@ -1,28 +1,35 @@
...
-      Delete
-    </va-button>
-  </div>
+  <va-list-item
+    tabindex="-1"
+    :disabled="disabled"
+    :aria-disabled="disabled"
+  >
+    <va-list-item-section>
+      <div class="va-file-upload-single-item">
```
Comment (RVitaly1978) [inline packages/ui/src/components/va-file-upload/VaFileUploadSingleItem/VaFileUploadSingleItem.vue:8]: Can we do it?
```suggestion
    <va-list-item-section class="va-file-upload-single-item">
```

**Review by RVitaly1978 — CHANGES_REQUESTED** [review]

**Review by RVitaly1978 — APPROVED** [review]
