### PR TITLE
[#1985] Fix `VaProgressBar` slot position

### LINKED ISSUE #1985: va-progress-bar won't locate the default slot inside itself even if there's enough space for it
image

Per @RVitaly1978 

Currently there are two scenarious for the default's slot behavior for the progress bar. It either is located inside the bar, or above it.

The idea is that if it's possible to fit the slot inside the bar, then it should go there, but if the slot won't fit there (as in case with small- and medium-sized bars), it goes above the bar.

Though the issue is that currently the only possible way to locate the slot inside the bar is to set the bar's size property to `large`. And, as you can see from the screenshot above, when you use some custom size (like 2rem) which is definitely larger than the `large` size, the slot won't go inside the bar. But ideally it should.

AFAICS, there exist 2 potential solutions for this issue:
1. Universal, but clutchy and tricky to implement and support: render the bar first, find its actual rendered size and compare it to the slot's rendered size. If the slot's size is smaller than the bar's size, fit the slot inside. Otherwise, put it on top.
2. The second solution is to provide a new prop, something like boolean `slot-inside`, which tells wheher it's a good idea for Vuestic to try to fit the slot inside the bar instead of locating it above the progress bar (which is, again, the default and the current behavior).

I personally like the 2nd approach more, though there's a fine line between over-implementing things and providing a lot of freedom for the developers. In other words, such a prop might be an overkill. Please, share your thoughts on the topic.

### PR DESCRIPTION
**Pull request by RVitaly1978**
## Description
close #1985

changes:
- [x] add boolean `content-inside` prop
- [x] add boolean `show-percent` prop
- [x] update examples and locales

image

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any feature but make things better)

### CODE REVIEW

**Review by rustem-nasyrov — APPROVED** [review]

**Review by aluarius — APPROVED** [review]

File: packages/ui/src/components/va-progress-bar/VaProgressBar.vue [hunk 1]
```diff
@@ -47,12 +53,12 @@ export default defineComponent({
     buffer: { type: Number, default: 100 },
     rounded: { type: Boolean, default: true },
     reverse: { type: Boolean, default: false },
+    slotInside: { type: Boolean, default: false },
```
Comment (m0ksem) [inline packages/ui/src/components/va-progress-bar/VaProgressBar.vue:56]: Which slot?

How about to rename it in `contentInside`, `percentInside` or simply `inside`?

**Review by m0ksem — APPROVED** [review]

File: packages/ui/src/components/va-progress-bar/VaProgressBar.vue (hunk 1 above)
Comment (RVitaly1978) [reply packages/ui/src/components/va-progress-bar/VaProgressBar.vue:56]: I choose `contentInside ` ))
