### PR TITLE
Fix#1814/outline button text color

### LINKED ISSUE #1814: text-color not working on outline button
**Vuestic-ui version:** 1.4.0

**Steps to reproduce**
```
<va-button outline text-color="#ff1100" class="mr-4">Red text</va-button>
```

**What is the expected behavior?**
Text should turn red

**What is the current behavior?**
Text color stays at it's default

**Other information**
I got the code directly from your documentation that even shows the bug and gives you a link to prove the bug in sandbox. If this is a known issue it should be stated in the docs.

### PR DESCRIPTION
**Pull request by m0ksem**
closes #1814

Before:
image
firefox_FfbUZY9wmb

After:
image
image

Here  is also some issue with sidebar, but I think we will fix it with https://github.com/epicmaxco/vuestic-ui/pull/1736 in different task.

### CODE REVIEW

File: packages/ui/src/composables/useTextColor.ts [hunk 1]
```diff
@@ -1,19 +1,25 @@
...
+  textColor: string,
+  color?: string
+}
+
+/**
+ * @param componentColor component color. By default `props.color`.
+ * @param isTransparent if transparent will return component color as text color.
+ * @returns Computed text color based on component's color if `props.textColor` if provided.
+ */
+export const useTextColor = (componentColor?: Ref<string> | undefined, isTransparent: boolean | Ref<boolean> = false) => {
```
Comment (RVitaly1978) [inline packages/ui/src/composables/useTextColor.ts:14]:
```suggestion
export const useTextColor = (componentColor?: Ref<string> | string | undefined, isTransparent: boolean | Ref<boolean> = false) => {
```

**Review by RVitaly1978 — APPROVED** [review]

File: packages/ui/src/composables/useTextColor.ts (hunk 1 above)
Comment (m0ksem) [reply packages/ui/src/composables/useTextColor.ts:14]: I think, if we remove string, this will force use to use reactive variable. I don't believe we would have a component with static background.

**Review by aluarius — APPROVED** [review]
