### PR TITLE
Fixed clipboard button.

### LINKED ISSUE #919: The error appears after clicking the Copy code button
* **What is the expected behavior?**
The code should be copied.

* **What is the current behavior?**
The error appears after clicking the Copy code button and code do not copy.

Снимок экрана 2021-07-05 в 11 03 04

Tested in google chrome

### PR DESCRIPTION
**Pull request by DieselTripleX**
## Description

Closes #919

Fixed clipboard button, using Clipboard API. Previously, v-clipboard plugin for nuxt was used for copy functional, but we rejected nuxt after moving from vue2 -> vue3.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any feature but make things better)

### CODE REVIEW

File: packages/docs/src/components/DocsNavigation.vue [hunk 1]
```diff
@@ -71,10 +71,17 @@ export default {
...
+    updateCopyButton(icon, text) {
+      this.copyIcon = icon
+      this.copyText = text
+    },
     copy () {
-      this.$clipboard(this.code)
-      this.copyIcon = 'fa fa-check'
-      this.copyText = 'Copied'
+      try {
+        window.navigator.clipboard.writeText(this.code)
```
Comment (m0ksem) [inline packages/docs/src/components/DocsNavigation.vue:80]: According to specification https://w3c.github.io/clipboard-apis/#dom-clipboard-writetext, write text is an async function. You should use `await` here to catch errors.
```suggestion
        await window.navigator.clipboard.writeText(this.code)
```

Can you check if I correct? Maybe this `await` can break your code 😄

**Review by m0ksem — CHANGES_REQUESTED** [review]
As I can see [Clipboard API](https://caniuse.com/mdn-api_clipboard_writetext) has partial support for all browsers. For security reasons, I think.

But, [Clipboard API WriteText](https://caniuse.com/mdn-api_clipboard_writetext) is supported everywhere, except IE 11.

A small change is required.

**Review by m0ksem — APPROVED** [review]

**Comment by asvae** [comment]
Thanks!
