### PR TITLE
Fix #971 Fix router anchor links in docs

### LINKED ISSUE #971: Following anchor links via router-link does not work correctly
* **What is the expected behavior?**
  - when a user clicks on a router-link with an anchor, there should be a transition to the top of the element with an anchor

* **What is the current behavior?**
  - if the anchor is on the current page, then the jump to the anchor is not performed (nothing happens)
  - if the anchor is on another page, then the transition to the page top is performed and not to the anchor 

* **Steps to reproduce, ideally also a screenshot or gif if it's a style issue**

* **Other information**

### PR DESCRIPTION
**Pull request by RVitaly1978**
## Description
close #971

Some of the changes:
  - if the anchor is on the current page, then the jump to the anchor is performed
  - if the anchor is on another page, then the transition to the anchor is performed
  - if the link without anchor is on another page, then the transition to the page top is performed

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Improvement/refactoring (non-breaking change that doesn't add any feature but make things better)

### CODE REVIEW

File: packages/docs/src/router/index.ts [hunk 1]
```diff
@@ -25,4 +25,16 @@ export const router = createRouter({
       children: routes.map((r) => ({ ...r, name: undefined })),
     },
   ],
+  // Good solution, but not working
```
Comment (asvae) [inline packages/docs/src/router/index.ts:28]: Remove this?

**Review by asvae — APPROVED** [review]

**Comment by asvae** [comment]
Cool!
