### PR TITLE
[#1751] Fix `render` and `dangerouslyUseHtmlString` props of `VaToast`

### LINKED ISSUE #1751: `VaToast` docs example with `render` prop gives errors (in develop branch)
**Vuestic-ui version:** 1.3.5

**Steps to reproduce**
develop branch: http://localhost:8081/en/ui-elements/toast#basic-usage

**What is the expected behavior?**
chrome-capture

**What is the current behavior?**
https://user-images.githubusercontent.com/55198465/167619509-7d0eb80d-e2d5-4a34-9678-c92abfeba56d.mov

**Other information**

### PR DESCRIPTION
**Pull request by RVitaly1978**
## Description
close #1751

changes:
- [x] fix `render` prop and add type
- [x] fix `dangerouslyUseHtmlString` (replace `html` prop)
- [x] update examples in docs and demos, update locales
- [x] remove redundant scss variables in source files

chrome-capture

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any feature but make things better)

### CODE REVIEW

File: packages/ui/src/components/va-toast/VaToast.vue [hunk 1]
```diff
@@ -11,21 +11,21 @@
       ref="rootElement"
     >
       <div class="va-toast__group">
-        <h2 v-if="title" class="va-toast__title" v-text="title" />
```
Comment (aluarius) [inline packages/ui/src/components/va-toast/VaToast.vue:14]: Why $props.[name] here and below? Your IDE swears on it cause of two defineComponent?

**Review by aluarius — APPROVED** [review]

File: packages/ui/src/components/va-toast/VaToast.vue (hunk 1 above)
Comment (RVitaly1978) [reply packages/ui/src/components/va-toast/VaToast.vue:14]: For convenience :)

**Comment by asvae** [comment]
Awesome! Merging.
