### PR TITLE
Fix #1156 #702 Textarea resize

### LINKED ISSUE #702: Fix textarea mixin
For some reason, text-area mixin has no access to `this.$refs`. Currently, text-area mixin uses the adjust-height method which can not access `this.$refs`. We need to rewrite this mixin to composition API.

Most likely this bug caused because of the `vue-class-component`.

### LINKED ISSUE #1156: Textarea autoresize doesn't work
http://vuestic-ui-demo.sub.asva.by/#/demo/va-input/VaInput.demo.vue

image

### PR DESCRIPTION
**Pull request by m0ksem**
## Description
closes #1156
closes #702
VEgUTz1le7

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Improvement/refactoring (non-breaking change that doesn't add any feature but make things better)

### CODE REVIEW

File: packages/ui/src/components/va-checkbox/VaCheckbox.vue [hunk 1]
```diff
@@ -22,8 +22,8 @@
       >
         <input
           ref="input"
-          :id="id"
-          :name="name"
+          :id="String(id)"
```
Comment (asvae) [inline packages/ui/src/components/va-checkbox/VaCheckbox.vue:25]: What is this for?

**Comment by asvae** [comment]
Doesn't look too good - 
image

**Comment by asvae** [comment]
Thanks!
