### PR TITLE
Fix sorting in the VaDataTable

### LINKED ISSUE #2497: VaDataTable doesn't work on SSR
**Vuestic-ui version:** 1.5.0

image

### PR DESCRIPTION
**Pull request by rustem-nasyrov**
Close #2497

## Description
- Refactored and fixed with it sorting issue on nuxt when `ssr` is truthy.

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] Improvement/refactoring (non-breaking change that doesn't add any feature but make things better)

### CODE REVIEW

File: packages/ui/src/components/va-data-table/hooks/useSortable.ts [hunk 1]
```diff
@@ -71,23 +71,24 @@ export default function useSortable (
...
+      ? columns.value.findIndex(({ name, sortable }) => sortBySync.value === name && sortable)
+      : -1
 
-    if (!column || !column.sortable) {
+    if (!column || !column.sortable || columnIndex === -1) {
       return filteredRows.value
     }
 
-    const columnIndex = columns.value.indexOf(column)
+    const sortingOrderRatio = sortingOrderSync.value === 'desc' ? -1 : 1
```
Comment (m0ksem) [inline packages/ui/src/components/va-data-table/hooks/useSortable.ts:82]: Is this move `sortingOrderRatio ` is important too? 🤔

File: packages/ui/src/components/va-data-table/hooks/useSortable.ts [hunk 2]
```diff
@@ -71,23 +71,24 @@ export default function useSortable (
     }
 
     const column = columns.value.find(column => column.name === sortBySync.value)
+    const columnIndex = column
+      ? columns.value.findIndex(({ name, sortable }) => sortBySync.value === name && sortable)
+      : -1
```
Comment (m0ksem) [inline packages/ui/src/components/va-data-table/hooks/useSortable.ts:76]:
```suggestion
      : -1
    const column = columns.value[columnIndex]
```

File: packages/ui/src/components/va-data-table/hooks/useSortable.ts [hunk 3]
```diff
@@ -71,23 +71,24 @@ export default function useSortable (
...
 
-    if (!column || !column.sortable) {
+    if (!column || !column.sortable || columnIndex === -1) {
```
Comment (m0ksem) [inline packages/ui/src/components/va-data-table/hooks/useSortable.ts:78]: Double check for column.sortable?

**Review by m0ksem — COMMENTED** [review]
This looks very the same from what it was before in my opinion? Can you explain what exactly is changed here?
